/**
 * Downloads every file in the library seed into a local folder tree that
 * mirrors the Google Drive structure, e.g.
 *
 *   library/AGILE/AGILE/02-AgileSoftwareDevelopment.pdf
 *
 * - Reads seeds/library-items.json (generated by gen-library-seed.ts).
 * - Resumable: files that already exist on disk are skipped; downloads are
 *   written to a .part file and renamed into place only on success.
 * - Concurrent downloads; failures are logged and reported, the rest continue.
 * - Handles Drive's large-file virus-scan confirmation page.
 *
 * Usage: npx tsx scripts/download-library.ts [outDir]
 *   (outDir defaults to the repo-root "library" folder)
 */
import { createWriteStream, existsSync } from "node:fs";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SEED = resolve(HERE, "..", "seeds", "library-items.json");
const OUT_ROOT = resolve(HERE, "..", "..", "library");

const CONCURRENCY = 5;

interface SeedItem {
  id: string;
  sourceKey: string;
  folderPath: string;
  name: string;
  kind: string;
  driveFileId: string;
  url: string;
  isProtected: boolean;
}

function sanitize(name: string): string {
  const cleaned = name
    // Control characters are invalid in local paths and must be stripped.
    // eslint-disable-next-line no-control-regex
    .replace(/[<>:"/\\|?*\u0000-\u001f]/g, "_")
    .replace(/[. ]+$/g, "")
    .trim();
  return (cleaned || "unnamed").slice(0, 160);
}

/** Resolves a destination path for a file, deduping names within its folder. */
function destFor(file: SeedItem, usedNames: Map<string, Set<string>>): string {
  const dir = resolve(OUT_ROOT, ...file.folderPath.split(" / ").map(sanitize).filter(Boolean));
  let name = sanitize(file.name);
  const taken = usedNames.get(dir) ?? new Set<string>();
  usedNames.set(dir, taken);
  if (taken.has(name.toLowerCase())) {
    let i = 2;
    const ext = name.includes(".") ? name.slice(name.lastIndexOf(".")) : "";
    const base = ext ? name.slice(0, name.lastIndexOf(".")) : name;
    while (taken.has(`${base} (${i})${ext}`.toLowerCase())) i += 1;
    name = `${base} (${i})${ext}`;
  }
  taken.add(name.toLowerCase());
  return join(dir, name);
}

async function fetchWithRedirects(url: string, redirectsLeft: number): Promise<Response> {
  const res = await fetch(url, { redirect: "manual" });
  if (
    (res.status === 301 || res.status === 302 || res.status === 303 || res.status === 307) &&
    redirectsLeft > 0
  ) {
    const location = res.headers.get("location");
    if (location) return fetchWithRedirects(location, redirectsLeft - 1);
  }
  return res;
}

/** Downloads a public Drive file; handles the confirm page for big files. */
async function downloadFile(file: SeedItem, dest: string): Promise<void> {
  const baseUrl = `https://drive.usercontent.google.com/download?id=${file.driveFileId}&export=download&confirm=t`;
  let res = await fetchWithRedirects(baseUrl, 5);

  const contentType = res.headers.get("content-type") ?? "";
  if (contentType.includes("text/html")) {
    // Large files hit a virus-scan confirmation page — follow its form.
    const text = await res.text();
    const action = text.match(/action="([^"]+)"/);
    const confirm = text.match(/name="confirm" value="([^"]+)"/);
    if (!action?.[1] || !confirm?.[1]) {
      throw new Error(`unexpected HTML response (${text.slice(0, 80)})`);
    }
    const actionUrl = action[1].includes("://")
      ? action[1]
      : `https://drive.usercontent.google.com${action[1]}`;
    const nextUrl = actionUrl.replace("{id}", file.driveFileId).replace("{confirm}", confirm[1]);
    res = await fetchWithRedirects(nextUrl, 5);
  }

  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  if (!res.body) throw new Error("no response body");

  const tmp = `${dest}.part`;
  await mkdir(dirname(dest), { recursive: true });
  const out = createWriteStream(tmp);
  const reader = res.body.getReader();
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (!out.write(value)) {
        await new Promise((resolveDrain) => out.once("drain", resolveDrain));
      }
    }
  } finally {
    reader.releaseLock();
  }
  await new Promise<void>((resolveWrite, rejectWrite) => {
    out.on("finish", resolveWrite);
    out.on("error", rejectWrite);
    out.end();
  });
  await rename(tmp, dest);
}

async function run(): Promise<void> {
  const args = process.argv.slice(2);
  const outRoot = args[0] ? resolve(args[0]) : OUT_ROOT;

  const seed = JSON.parse(await readFile(SEED, "utf8")) as SeedItem[];
  const files = seed.filter((i) => i.kind === "file");
  console.log(`Seed: ${seed.length} entries, ${files.length} files → ${outRoot}`);

  const usedNames = new Map<string, Set<string>>();
  const jobs = files.map((file) => ({ file, dest: destFor(file, usedNames) }));
  const alreadyPresent = jobs.filter((j) => existsSync(j.dest)).length;

  const failures: { name: string; dest: string; error: string }[] = [];
  let processed = 0;
  let next = 0;

  async function worker(): Promise<void> {
    while (true) {
      const index = next;
      next += 1;
      if (index >= jobs.length) return;
      const { file, dest } = jobs[index]!;
      if (existsSync(dest)) {
        processed += 1;
        continue;
      }
      try {
        await downloadFile(file, dest);
        processed += 1;
      } catch (err) {
        failures.push({
          name: file.name,
          dest,
          error: err instanceof Error ? err.message : String(err),
        });
        processed += 1;
      }
      if (processed % 50 === 0) {
        console.log(`  ${processed}/${jobs.length} processed (${failures.length} failed)`);
      }
    }
  }

  const workers = Array.from({ length: CONCURRENCY }, () => worker());
  await Promise.all(workers);

  console.log(
    `Done: ${jobs.length} files, ${alreadyPresent} already present, ${processed - alreadyPresent - failures.length} downloaded, ${failures.length} failed.`,
  );
  if (failures.length > 0) {
    await writeFile(
      join(outRoot, "download-errors.log"),
      failures.map((f) => `${f.name}\t${f.dest}\t${f.error}`).join("\n"),
    );
    console.log(`Failures logged to ${join(outRoot, "download-errors.log")}:`);
    for (const f of failures.slice(0, 25)) {
      console.log(`  - ${f.name}: ${f.error}`);
    }
  }
}

void run();
