/**
 * Generates backend/src/lib/assistant-knowledge.generated.ts — the factual
 * block the public site assistant is grounded on.
 *
 * The assistant is only allowed to state what is in here. Fees, durations,
 * payment terms and contact details therefore come from the same modules the
 * marketing site renders, so the bot cannot quote a price the academy does not
 * honour (the failure mode that produced the "which price is real?" confusion).
 *
 * Run:  npx tsx backend/scripts/gen-assistant-knowledge.ts
 * Also:  cd backend && npm run gen:knowledge   (after changing course data)
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { allCourses } from "../../src/data/academy/catalog";
import {
  NEXT_COHORTS,
  WHAT_TO_BRING,
  longPaymentPlans,
  longformPrograms,
  shortPaymentPlans,
} from "../../src/data/academy/longform";
import { faqs } from "../../src/data/site";

const naira = (n: number) => `₦${n.toLocaleString("en-NG")}`;

/** Fixed facts — verified against the live site and this repo's docs. */
const FACTS = {
  legalName: "Cyber Elias Academy Ltd (RC 8413776)",
  address: "24/26 Ebony Road, off Rumuola Road, Port Harcourt, Rivers State",
  hours: "Monday–Saturday, 8:00–20:00 WAT",
  phone: "+234 905 862 8386",
  email: "help@cea.ng",
  website: "https://www.cea.ng",
  applyUrl: "https://www.cea.ng/apply",
  bank: "Cyber Elias Academy Ltd · UBA · account number 1028649972 (bank transfer)",
  paystack: "Card, bank or USSD via the secure checkout on cea.ng/apply",
} as const;

function courseSection(): string {
  return allCourses
    .map(
      (c) =>
        `- ${c.title} | ${naira(c.fee)} | ${c.weeks} week${c.weeks === 1 ? "" : "s"}, ${c.sessionsPerWeek}×/week | ${c.level} | ${c.hook}`,
    )
    .join("\n");
}

function diplomaSection(): string {
  return longformPrograms
    .map(
      (p) =>
        `- ${p.title} | ${naira(p.fee)} | ${p.months} months, 3 days/week (${p.weeks} weeks) | ${p.tagline}`,
    )
    .join("\n");
}

function planSection(): string {
  const short = shortPaymentPlans.map((p) => `${p.label} (${p.detail})`).join("; ");
  const long = longPaymentPlans.map((p) => `${p.label} (${p.detail})`).join("; ");
  return `Short courses: ${short}. Diplomas: ${long}.`;
}

function faqSection(): string {
  // Keep the site's public Q&As that prospects actually ask, trimmed of any
  // duplicates by question text.
  const seen = new Set<string>();
  const picked = faqs
    .filter((f) => {
      const key = f.q.toLowerCase();
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .slice(0, 14);
  return picked.map((f) => `Q: ${f.q}\nA: ${f.a}`).join("\n");
}

const knowledge = `# Cyber Elias Academy — facts you may state

You are the public assistant for Cyber Elias Academy, a digital-skills training
centre in Port Harcourt, Nigeria. Answer only from the facts below. If something
is not here, say you don't have that detail and hand over to a human
(WhatsApp or call ${FACTS.phone}, or email ${FACTS.email}). Never invent a price, discount,
start date, certificate claim or policy. Fees are in Nigerian Naira.

## Contact
- ${FACTS.legalName}
- ${FACTS.address}
- ${FACTS.hours}
- Phone / WhatsApp: ${FACTS.phone} (call or WhatsApp)
- Email: ${FACTS.email} · Website: ${FACTS.website}
- Certificates are verifiable at cea.ng/certificates/verify. Say what a course
  delivers; do not claim government or university accreditation.

## Payments
- Online: ${FACTS.paystack}
- Direct transfer: ${FACTS.bank} — after paying, send the receipt on WhatsApp
  and the seat is confirmed the same day.
- ${planSection()}
- No application fee. Fees cover class materials and the published notes.

## Short courses (${allCourses.length})
Each is taught in person at the academy, with an online option where noted.
${courseSection()}

## Diploma programmes (${longformPrograms.length}) — cohort based
${diplomaSection()}

## Dates
- Short courses: ${NEXT_COHORTS.short}
- Diplomas: ${NEXT_COHORTS.long}

## What to bring
${WHAT_TO_BRING.map((w) => `- ${w}`).join("\n")}

## Frequently asked
${faqSection()}
`;

// A template literal (not a JSON string) keeps the generated file
// Prettier-clean, so `prettier --check .` stays green in CI.
const escaped = knowledge.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
const out = `/*
 * GENERATED by backend/scripts/gen-assistant-knowledge.ts — do not edit by hand.
 * Re-run after any change to course fees, dates, payment terms or FAQs:
 *   cd backend && npm run gen:knowledge
 */
export const ASSISTANT_KNOWLEDGE = \`${escaped}\`;
`;

const target = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "lib",
  "assistant-knowledge.generated.ts",
);
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out, "utf8");

console.log(
  `Wrote ${target} (${allCourses.length} courses, ${longformPrograms.length} diplomas, ${knowledge.length} chars)`,
);
