/**
 * Generates backend/src/lib/assistant-knowledge.generated.ts — the factual
 * block the public site assistant is grounded on.
 *
 * The assistant is only allowed to state what is in here. Fees, durations,
 * payment terms and contact details therefore come from the same modules the
 * marketing site renders, so the bot cannot quote a price the academy does not
 * honour (the failure mode that produced the "which price is real?" confusion).
 *
 * Run:  npx tsx backend/scripts/gen-assistant-knowledge.ts
 * Also:  cd backend && npm run gen:knowledge   (after changing course data)
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { flyerCourses, rotatingCourses } from "../../src/data/academy/catalog";
import { WHAT_TO_BRING, shortPaymentPlans } from "../../src/data/academy/longform";
import { faqs } from "../../src/data/site";

const naira = (n: number) => `₦${n.toLocaleString("en-NG")}`;

/** Fixed facts — verified against the live site and this repo's docs. */
const FACTS = {
  legalName: "Cyber Elias Academy Ltd (RC 8413776)",
  address: "24/26 Ebony Road, off Rumuola Road, Port Harcourt, Rivers State",
  hours: "Monday–Saturday, 8:00–20:00 WAT",
  phone: "+234 905 862 8386",
  email: "help@cea.ng",
  website: "https://www.cea.ng",
  applyUrl: "https://www.cea.ng/apply",
  bank: "Cyber Elias Academy Ltd · UBA · account number 1028649972 (bank transfer)",
  paystack: "Card, bank or USSD via the secure checkout on cea.ng/apply",
} as const;

function courseSection(courses: typeof flyerCourses): string {
  return courses
    .map(
      (c) =>
        `- ${c.title} | ${naira(c.fee)} | ${c.weeks} week${c.weeks === 1 ? "" : "s"}, ${c.sessionsPerWeek}×/week | ${c.level} | ${c.hook}`,
    )
    .join("\n");
}

function planSection(): string {
  return shortPaymentPlans.map((p) => `${p.label} (${p.detail})`).join("; ");
}

function faqSection(): string {
  // Keep the site's public Q&As that prospects actually ask, trimmed of any
  // duplicates by question text.
  const seen = new Set<string>();
  const picked = faqs
    .filter((f) => {
      const key = f.q.toLowerCase();
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .slice(0, 14);
  return picked.map((f) => `Q: ${f.q}\nA: ${f.a}`).join("\n");
}

const knowledge = `# Cyber Elias Academy — facts you may state

You are the public assistant for Cyber Elias Academy, a digital-skills training
centre in Port Harcourt, Nigeria. Answer only from the facts below. If something
is not here, say you don't have that detail and hand over to a human
(WhatsApp or call ${FACTS.phone}, or email ${FACTS.email}). Never invent a price, discount,
start date, certificate claim or policy. Fees are in Nigerian Naira.

## Contact
- ${FACTS.legalName}
- ${FACTS.address}
- ${FACTS.hours}
- Phone / WhatsApp: ${FACTS.phone} (call or WhatsApp)
- Email: ${FACTS.email} · Website: ${FACTS.website}
- Certificates are verifiable at cea.ng/certificates/verify. Say what a course
  delivers; do not claim government or university accreditation.

## Payments
- Online: ${FACTS.paystack}
- Direct transfer: ${FACTS.bank} — report the transfer from your application status page. Finance verifies it against the bank statement before confirming payment; admissions confirms course availability, your place and start date separately.
- Short-course payment plans: ${planSection()}
- No application fee. Fees cover class materials and the published notes.

## Core short courses (${flyerCourses.length})
These are the courses on the Academy flyer and the standard short-course application form.
${courseSection(flyerCourses)}

## Rotating specialist short courses (${rotatingCourses.length})
These are listed separately from the core flyer offer. Do not imply a current start date or availability; ask admissions to confirm whether and when a specific course is running.
${courseSection(rotatingCourses)}

## Longer programme plans
A programme listing or development/mock cohort entry is not proof that a longer programme is currently deliverable. Do not describe these programmes as open or quote dates from mock/static data. Direct enquiries to admissions for current status.

## Start dates
Only state a start date when the live admissions cohort register returns a course-specific cohort with status scheduled. A generic rolling-intake row, a preferred date entered by an applicant, or a mock fixture is not a confirmed date. If no course-specific date is listed, say so and ask admissions to confirm availability.

## What to bring
${WHAT_TO_BRING.map((w) => `- ${w}`).join("\n")}

## Frequently asked
${faqSection()}
`;

// A template literal (not a JSON string) keeps the generated file
// Prettier-clean, so `prettier --check .` stays green in CI.
const escaped = knowledge.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
const out = `/*
 * GENERATED by backend/scripts/gen-assistant-knowledge.ts — do not edit by hand.
 * Re-run after any change to course fees, dates, payment terms or FAQs:
 *   cd backend && npm run gen:knowledge
 */
export const ASSISTANT_KNOWLEDGE = \`${escaped}\`;
`;

const target = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "lib",
  "assistant-knowledge.generated.ts",
);
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out, "utf8");

console.log(
  `Wrote ${target} (${flyerCourses.length} core courses, ${rotatingCourses.length} rotating courses, ${knowledge.length} chars)`,
);
