-- 0040_submissions_columns.sql - Add owner/scoping columns to submissions.
--
-- SUPERSEDED BY 0009: this migration originally re-added
-- student_user_id / assignment_id / feedback / graded_at / graded_by and
-- idx_submissions_assignment, all of which migration 0009 already creates.
-- On any database that ran 0009 (every environment, since it is part of the
-- base chain) re-running these statements fails with
-- "duplicate column name: student_user_id", which broke `wrangler d1
-- migrations apply` on fresh databases. The file is intentionally kept as a
-- documented no-op so existing migration ledgers stay consistent.
--
-- Columns provided by 0009 (authoritative):
--   submissions.student_user_id TEXT
--   submissions.assignment_id   TEXT
--   submissions.feedback        TEXT NOT NULL DEFAULT ''
--   submissions.graded_by       TEXT
--   submissions.graded_at       TEXT
--   INDEX idx_submissions_assignment ON submissions(assignment_id)
--
-- NOTE: 0009 declares student_user_id without an FK (SQLite cannot add
-- constraints retroactively); ownership is enforced in the API layer
-- (assignments submit/grade endpoints scope rows by student_user_id).
