-- DEMO LOGINS — generated by scripts/gen-demo-users.ts
-- Apply to LOCAL:  npx wrangler d1 execute DB --local  --file seeds/demo-users.sql
-- Apply to REMOTE: npx wrangler d1 execute DB --remote --file seeds/demo-users.sql
-- Remove (all of them): npx wrangler d1 execute DB --remote --file seeds/demo-users-remove.sql
--
-- These are test accounts for exercising role workspaces. Delete them when done.
-- Safe to re-run: the upsert only ever updates rows whose id starts with 'demo-'.

-- Roles: student, instructor, admissions, finance, admin, director, hr, ops, it, marketing, growth, design, localization, conversion-copy, product-marketing, behavioral-design, department, mentor, alumni, parent, client, employer, partner, supplier, ngo, government, receptionist, intern, volunteer, dev

INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-student', 'Ada Okafor (Student)', 'student@demo.cea.ng', 'pbkdf2$100000$X7owr9lS9c4mC+fEa1PT0g==$z9FNU7RJUCh5Gc2Dg7gkCb5o4Okl8DgKg2X5lmaXmPg=', 'student', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-instructor', 'Musa Ibrahim (Instructor)', 'instructor@demo.cea.ng', 'pbkdf2$100000$XKtvC8JYzg4CaALhk9f3wQ==$XTYm5+/OGxrvcJTPieM3kznozhwp9U3lR1IyaFhXtFg=', 'instructor', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-admissions', 'Chiamaka Eze (Admissions)', 'admissions@demo.cea.ng', 'pbkdf2$100000$n5INDgOV3iQnUODJpXx7/Q==$hC5Bw9AujnLG/+ojlR1yZCCr4mc/AK0x8EiftGdOD/4=', 'admissions', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-finance', 'Tolu Adeyemi (Finance)', 'finance@demo.cea.ng', 'pbkdf2$100000$kSjNPZJ1SjQFHq46DRLxvQ==$yYQZu93+1jJ7gZ+QUT6PxytLuybjpB1dc1+Xb6QCaNs=', 'finance', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-admin', 'Ellis Dennis (Admin)', 'admin@demo.cea.ng', 'pbkdf2$100000$eHqu8iPlskxeFvb3E3j6/g==$xhkpnyCXpxgc1MQ5UlO6Qmfn5uqx0icBgkQNO/PeOpw=', 'admin', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-director', 'Graham Ellis Dennis (Director)', 'director@demo.cea.ng', 'pbkdf2$100000$jAx0shpvzZOQawLvmnnj/g==$ALYubIAl07wmlVhv+14U0Jk8bQlEkfiadGuCBSIa+FI=', 'director', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-hr', 'Zainab Bello (HR)', 'hr@demo.cea.ng', 'pbkdf2$100000$ufxdNcfNoee7JYawv6D/gQ==$Wrx6Ihdq1S7s3ZrqM1yKDM94KwZcuv/6SXQcUWWJEQA=', 'hr', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-ops', 'Ifeanyi Nwosu (Operations)', 'ops@demo.cea.ng', 'pbkdf2$100000$3Spc5/y6V7L2SGQzEplpBg==$ZyTfWGhi9WaT80k9j/IIhOmxdK84cAG8L41dUgr4Ueg=', 'ops', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-it', 'Emeka Okafor (IT)', 'it@demo.cea.ng', 'pbkdf2$100000$Pkt6ETWBaPBuAnotf0bYyA==$GU6HzCh/8wul87Dn6+Ex8SlYxAq6ati4PLasypKoaSo=', 'it', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-marketing', 'Bisi Adeleke (Marketing)', 'marketing@demo.cea.ng', 'pbkdf2$100000$EihCDJZM5MkDOvNbXydYfw==$CCU9C2vOf0PC6PX20nTRL9IY1UteROxBJPu6JUYmKq0=', 'marketing', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-growth', 'Ngozi Umeh (Growth)', 'growth@demo.cea.ng', 'pbkdf2$100000$FwVlSgfsZy7eh8q+JoxGmA==$z1H03k6ZxkkYvI82ARwlR+mEiXVJXt0J6+UrwCQAd/w=', 'growth', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-design', 'Kelechi Obi (Design)', 'design@demo.cea.ng', 'pbkdf2$100000$chBRdDL+7GAAM+6IRs3N3A==$aAfPLh15AgoSf9+8CjGUzTxp4p5RWJq0omc4KwUdvUc=', 'design', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-localization', 'Fatima Sani (Localization)', 'localization@demo.cea.ng', 'pbkdf2$100000$sfvW+gSbHZGGFM7zW7FJwA==$4zvTEe7FaLOXH8fvhTZy+j+Y57LSFH/lkeL4Sv2zAos=', 'localization', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-conversion-copy', 'Segun Alabi (Conversion Copy)', 'conversion-copy@demo.cea.ng', 'pbkdf2$100000$txf93d+VJeudmjWuyOL6QA==$IkHQwuQ44AL/e4TG3Hz/Q/T4zfcmx96YmTjgyc7DaE4=', 'conversion-copy', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-product-marketing', 'Amara Nnamdi (Product Marketing)', 'product-marketing@demo.cea.ng', 'pbkdf2$100000$uDRxyzkuBOFdGuIcMvwLqg==$h+oKedEvVuyHJ/vDVY+Y6+BkvrIeOM/zonhRqasihHA=', 'product-marketing', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-behavioral-design', 'Yemi Fashola (Behavioral Design)', 'behavioral-design@demo.cea.ng', 'pbkdf2$100000$pB6c7Vn1Rf26P7/4XwHtTw==$/40P+GrzXfHC1wmycZWJ7G5XiQdYSCe52nxA9dY1C34=', 'behavioral-design', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-department', 'Hauwa Garba (Department)', 'department@demo.cea.ng', 'pbkdf2$100000$flTmbY67irSPAiScDlfcMg==$xa++XDFnTCgpcGZ1YLzDNCpvZxmshKukuPlVbXij3LE=', 'department', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-mentor', 'Peter Ekong (Mentor)', 'mentor@demo.cea.ng', 'pbkdf2$100000$TDHlu2/NI82S0maNnacIjg==$Yr829wUZMZ9P4JhsTV3CTKuy2YvrO3b+SSw1A2p9kP8=', 'mentor', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-alumni', 'Rita Bassey (Alumni)', 'alumni@demo.cea.ng', 'pbkdf2$100000$UrcVoZBWXxXiZpWnDuLnBQ==$3B4FM6k3v/OXgJc3yFsKO7d8lHC29YWkic+2B+3snzs=', 'alumni', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-parent', 'Grace Okafor (Parent)', 'parent@demo.cea.ng', 'pbkdf2$100000$enRW9mO6tPUbnry+x7rzqg==$q5QnqpUSTym8GiMzVKprigLKIVrFb4qLdCjSILnUVPw=', 'parent', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-client', 'Dapo Ajayi (Client)', 'client@demo.cea.ng', 'pbkdf2$100000$fDQpGkpo4cay8yk5Gg5zIw==$3EFdUhPINbasa49BxcBGdFR1KoozwWuCgu1dMf6grCE=', 'client', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-employer', 'Nkechi Nwankwo (Employer)', 'employer@demo.cea.ng', 'pbkdf2$100000$UOG2Z7fC0Tm46Qe+U8Vv8w==$ZztTe7TX9vx0jzI5eEvy+Dq6y0tmN5aKBVCLa++xEPo=', 'employer', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-partner', 'Sadiq Yusuf (Partner)', 'partner@demo.cea.ng', 'pbkdf2$100000$fzF62q4LclQw0Qc5xjH+aQ==$L7nA1kuUm8Pzs7IYc6RRsJmATzNdYAmv7mzD2X/qqaw=', 'partner', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-supplier', 'Uche Kalu (Supplier)', 'supplier@demo.cea.ng', 'pbkdf2$100000$H4J6UZbTA32SfptEc5Olhg==$Qi4WljmOIcL+IoaladS2LEK/w8OD5RiXafzMFKjVHDY=', 'supplier', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-ngo', 'Blessing Ade (NGO)', 'ngo@demo.cea.ng', 'pbkdf2$100000$MciiI5N2XGgUgKcG0NI1yQ==$YlGvlh7P47blTAx8QdEkbZhrqLfpfmkUqI1ayOY0gVs=', 'ngo', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-government', 'Rivers State Compliance (Government)', 'government@demo.cea.ng', 'pbkdf2$100000$Kh9tfe09bnHLHEfWl6kSOA==$cfRf1ZC/QZ5+6wAVdMTDxy1Cf13wx1/mDZMDZ/EWx/Q=', 'government', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-receptionist', 'Joy Etim (Receptionist)', 'receptionist@demo.cea.ng', 'pbkdf2$100000$g3lbBabvdUvFWVbirKtdiw==$dY1OxoSfFCYm4l+84FMnopOMHhAEXF+RvSHoSLi4ZOg=', 'receptionist', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-intern', 'Sam Okon (Intern)', 'intern@demo.cea.ng', 'pbkdf2$100000$Z7NluQ1UDW2WzYaCsPbUuw==$swjPTe/+SC7OsZ6gq47pakxXXYz71JFnyvHh8zJmIvo=', 'intern', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-volunteer', 'Peace Danjuma (Volunteer)', 'volunteer@demo.cea.ng', 'pbkdf2$100000$GaZywGzOHWWgxVvjrbegGQ==$4hadXBtoJcEh6NUwyR8QQbWjkTcSDfMkcyLYSReplXs=', 'volunteer', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';
INSERT INTO users (id, name, email, password_hash, role_key, status, email_verified_at, created_at, updated_at)
VALUES ('demo-dev', 'Chidi Anyanwu (Dev)', 'dev@demo.cea.ng', 'pbkdf2$100000$Gm5i4gcGERKteEb5/CpuOA==$EijyLLobbbnRAr+X7W33OSkFMVDvH+m/41UE//G4id8=', 'dev', 'active', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z', '2026-10-02T10:35:06.730Z')
ON CONFLICT(email) DO UPDATE SET
  name = excluded.name,
  password_hash = excluded.password_hash,
  role_key = excluded.role_key,
  status = 'active',
  email_verified_at = COALESCE(users.email_verified_at, excluded.email_verified_at),
  updated_at = excluded.updated_at
WHERE users.id LIKE 'demo-%';

-- Sign in at https://www.cea.ng/auth/sign-in (email above + the password you passed).
-- In local mock mode (no VITE_API_URL) the app ships its own role switcher; these
-- accounts are for the live/staging Worker where sessions are real.
