/* Seed wrapper for department-data.sql (manual — mirrors the SQL file). */
export const seedDepartmentSql = String.raw`-- Seed: Department dashboard.
INSERT OR IGNORE INTO dep_hub (id, metric, value_label, delta, sort_order) VALUES ('dep-hb-01', 'Reports (year)', '12', '4 per quarter', 1), ('dep-hb-02', 'Completion rate', '92%', '+3 pts YoY', 2), ('dep-hb-03', 'Placement rate', '84%', 'within 6 months', 3), ('dep-hb-04', 'Exports (30d)', '6', 'by stakeholders', 4);
INSERT OR IGNORE INTO dep_reports (id, title, detail, status, sort_order) VALUES ('dep-rp-01', 'Student outcomes · Q2 2026', '92% completion · 84% placement', 'Published', 1), ('dep-rp-02', 'Instructor performance · Q2', 'Avg score 4.6 · 14 observations', 'Published', 2), ('dep-rp-03', 'Curriculum audit · draft', 'Due Aug 20 · 3 programs', 'Draft', 3);
INSERT OR IGNORE INTO dep_observations (id, title, detail, status, sort_order) VALUES ('dep-ob-01', 'Class observation — Mr. Adeyemi', 'Backend & APIs · Scheduled Aug 11', 'Scheduled', 1), ('dep-ob-02', 'Class observation — Ms. Chidera', 'DevOps Fundamentals · Scheduled Aug 13', 'Scheduled', 2), ('dep-ob-03', 'Course evaluation — Design Systems', 'Cohort 15 · Closed Jul 30 · 4.7★', 'Completed', 3);
INSERT OR IGNORE INTO dep_faculty (id, name, courses, students, workload, rating, sort_order) VALUES ('dep-fa-01', 'Mr. Adeyemi', 4, 62, '85%', '4.8', 1), ('dep-fa-02', 'Ms. Chidera', 3, 48, '70%', '4.6', 2), ('dep-fa-03', 'Mr. Bello', 3, 55, '78%', '4.7', 3), ('dep-fa-04', 'Mrs. Eze', 2, 34, '52%', '4.4', 4);
INSERT OR IGNORE INTO dep_cohorts (id, name, enrolled, capacity, pct, status, sort_order) VALUES ('dep-ch-01', 'Cohort 15 — Full-Stack', 48, 50, 96, 'Active', 1), ('dep-ch-02', 'Cohort 16 — Full-Stack', 42, 50, 84, 'Admitting', 2), ('dep-ch-03', 'Cohort 14 — DevOps', 36, 40, 90, 'Active', 3), ('dep-ch-04', 'Cohort 16 — Product Design', 30, 40, 75, 'Admitting', 4);
INSERT OR IGNORE INTO dep_programs (id, name, version, year, status, sort_order) VALUES ('dep-pg-01', 'Full-Stack Software Development', 'v3.1', '2026', 'Active', 1), ('dep-pg-02', 'Cloud Engineering & DevOps', 'v2.4', '2026', 'In review', 2), ('dep-pg-03', 'Product & UI/UX Design', 'v2.0', '2025', 'Active', 3), ('dep-pg-04', 'Data & AI', 'v1.0', 'draft', 'Draft', 4);
INSERT OR IGNORE INTO dep_events (id, title, date_label, status, sort_order) VALUES ('dep-ev-01', 'Mid-term assessments', 'Aug 17–21 · all programs', 'Upcoming', 1), ('dep-ev-02', 'Industry guest lecture', 'Aug 24 · 2:00 PM · Cloud track', 'Scheduled', 2), ('dep-ev-03', 'Graduation rehearsal', 'Sep 05 · 10:00 AM · Main hall', 'Scheduled', 3);
INSERT OR IGNORE INTO dep_approvals (id, title, requester, date_label, status, sort_order) VALUES ('dep-ap-01', 'Curriculum update · Frontend track', 'Instructor Adesuwa', 'Jul 30', 'Pending', 1), ('dep-ap-02', 'New course · Cloud Fundamentals', 'Instructor Tobi', 'Jul 29', 'Pending', 2), ('dep-ap-03', 'Leave request · Ngozi E.', 'Instructor', 'Jul 28', 'Approved', 3);
`;
