/* Seed wrapper for it-data.sql (manual — mirrors the SQL file). */
export const seedItSql = String.raw`INSERT OR IGNORE INTO it_tickets (id, subject, reporter, priority, sla, elapsed, status, sort_order) VALUES ('TKT-1042', 'Projector fails in Lab 2', 'Ms. Chidera', 'P1', 'SLA 2h', '1h elapsed', 'assigned', 0), ('TKT-1041', 'New starter laptop setup', 'Admissions officer', 'P2', 'SLA 24h', '3h elapsed', 'in progress', 1), ('TKT-1040', 'WiFi dropouts — Block C', 'Facilities', 'P1', 'SLA 2h', '30m elapsed', 'investigating', 2), ('TKT-1039', 'Printer toner request', 'Store keeper', 'P3', 'SLA 72h', '10h elapsed', 'queued', 3), ('TKT-1038', 'Whiteboard camera pairing', 'Mrs. Obi', 'P2', 'SLA 24h', '5h elapsed', 'solved', 4);
INSERT OR IGNORE INTO it_ticket_events (id, ticket_id, event, when_text, sort_order) VALUES ('ev-17', 'TKT-1042', 'Ticket created', 'Today 08:30', 0), ('ev-18', 'TKT-1042', 'Assigned to you', 'Today 08:45', 1), ('ev-19', 'TKT-1042', 'Remote check — projector confirmed faulty', 'Today 09:10', 2);
INSERT OR IGNORE INTO it_ticket_events (id, ticket_id, event, when_text, sort_order) VALUES ('ev-16', 'TKT-1041', 'Ticket created', 'Yesterday 15:20', 0), ('ev-15', 'TKT-1041', 'Laptop picked from store', 'Yesterday 16:05', 1);
INSERT OR IGNORE INTO it_articles (id, title, views, helpful_pct, category, sort_order) VALUES ('art-01', 'WiFi onboarding — staff', 412, 96, 'network', 0), ('art-02', 'Printer setup guide', 318, 91, 'printers', 1), ('art-03', 'Laptop provisioning checklist', 204, 88, 'hardware', 2);
INSERT OR IGNORE INTO it_assets (id, name, assigned_to, category, status, sort_order) VALUES ('ast-01', 'Laptop · HP EliteBook · #L-0142', 'Ms. Chidera', 'laptop', 'in use', 0), ('ast-02', 'Laptop · Dell Latitude · #L-0143', 'New starter', 'laptop', 'provisioning', 1), ('ast-03', 'Server · App node 2', 'Infra', 'server', 'healthy', 2), ('ast-04', 'Monitor · Dell 24" · #M-0211', 'Accounts', 'peripheral', 'in use', 3), ('ast-05', 'Laptop · Lenovo ThinkPad · #L-0144', 'J. Okonkwo', 'laptop', 'repair', 4);
INSERT OR IGNORE INTO it_licenses (id, product, seats, used, renews, status, sort_order) VALUES ('lic-01', 'Adobe Creative Cloud', 24, 20, 'Renews Oct 2026', 'active', 0), ('lic-02', 'Microsoft 365', 120, 96, 'Renews Jan 2027', 'active', 1), ('lic-03', 'Figma Pro', 30, 18, 'Renews Sep 2026', 'active', 2), ('lic-04', 'Notion Team', 40, 26, 'Renews Dec 2026', 'active', 3);
INSERT OR IGNORE INTO it_services (id, name, uptime, latency, status, sort_order) VALUES ('svc-01', 'Learning platform', '99.98%', '23 ms', 'healthy', 0), ('svc-02', 'Portal + API', '99.95%', '41 ms', 'healthy', 1), ('svc-03', 'Campus WiFi', '98.2%', '—', 'healthy', 2), ('svc-04', 'Video conferencing', '99.1%', '—', 'degraded', 3);
INSERT OR IGNORE INTO it_windows (id, title, window_text, status, sort_order) VALUES ('win-01', 'Platform maintenance', 'Aug 8 · 02:00–04:00', 'scheduled', 0), ('win-02', 'Backup infrastructure upgrade', 'Aug 15 · 01:00–03:00', 'scheduled', 1), ('win-03', 'WiFi controller firmware', 'Jul 26 · completed', 'done', 2);
INSERT OR IGNORE INTO it_sessions (id, name, detail, status, sort_order) VALUES ('rs-01', 'Ms. Chidera — Lab 2 projector', 'Active · 12 min', 'live', 0), ('rs-02', 'Mrs. Obi — Wi-Fi dropouts', 'Scheduled 14:30', 'upcoming', 1), ('rs-03', 'Registrar — printer queue', 'Completed · 8 min', 'done', 2);
INSERT OR IGNORE INTO it_templates (id, title, uses, status, sort_order) VALUES ('tpl-01', 'New starter — full setup', 12, 'active', 0), ('tpl-02', 'WiFi troubleshooting', 24, 'active', 1), ('tpl-03', 'Printer / peripheral fault', 9, 'active', 2), ('tpl-04', 'Account access reset', 5, 'draft', 3);
INSERT OR IGNORE INTO it_accounts (id, name, role, status, sort_order) VALUES ('usr-01', 'Ms. Chidera', 'Instructor · DevOps', 'active', 0), ('usr-02', 'New starter', 'Admissions officer', 'awaiting invite', 1), ('usr-03', 'J. Okonkwo', 'Data analyst', 'offboarded', 2), ('usr-04', 'Mrs. Obi', 'Learning design', 'active', 3);
`;