/* Seed wrapper for mentor-dashboard-data.sql (manual — mirrors the SQL file). */
export const seedMentorDashboardSql = String.raw`INSERT OR IGNORE INTO mnt_mentees (id, mentor_id, name, track, cohort, since_date, status, sort_order) VALUES ('mn-ada', 'mentor-1', 'Ada Okafor', 'Backend specialisation', 'Cohort 15', 'Feb 2026', 'active', 0), ('mn-tobi', 'mentor-1', 'Tobi Adeyemi', 'DevOps', 'Cohort 15', 'Feb 2026', 'active', 1), ('mn-zainab', 'mentor-1', 'Zainab Yusuf', 'Product design', 'Cohort 16', 'Jun 2026', 'active', 2);
INSERT OR IGNORE INTO mnt_sessions (id, mentor_id, mentee_id, title, datetime_text, mode, status, notes, sort_order) VALUES ('ms-01', 'mentor-1', 'mn-ada', 'Ada Okafor — goal review', 'Fri, Aug 21 · 16:00', 'Video', 'upcoming', 'Focus: NaijaEats demo-day checklist, EXPLAIN practice, follow-up booking.', 0), ('ms-02', 'mentor-1', 'mn-tobi', 'Tobi Adeyemi — exam prep', 'Sat, Aug 22 · 11:00', 'On campus', 'upcoming', 'Review CI/CD exam pattern and practice exercises.', 1), ('ms-03', 'mentor-1', 'mn-zainab', 'Zainab Yusuf — portfolio feedback', 'Tue, Aug 25 · 14:30', 'Video', 'upcoming', 'Portfolio v2 review — case study depth and copy.', 2), ('ms-04', 'mentor-1', 'mn-ada', 'Ada Okafor — mock interview', 'Thu, Jul 28 · 15:00', 'Video', 'completed', 'Strong system design answers. Book follow-up on behavioural questions.', 3), ('ms-05', 'mentor-1', 'mn-tobi', 'Tobi Adeyemi — career check-in', 'Mon, Jul 14 · 12:00', 'On campus', 'completed', 'Confirmed path to DevOps cert. Shared study roadmap.', 4);
INSERT OR IGNORE INTO mnt_session_actions (id, session_id, title, done, sort_order) VALUES ('ma-01', 'ms-01', 'Share demo-day checklist with Ada', 1, 0), ('ma-02', 'ms-01', 'Send EXPLAIN practice exercise', 1, 1), ('ma-03', 'ms-01', 'Book follow-up interview prep', 0, 2), ('ma-04', 'ms-01', 'Endorse Database Design skill', 0, 3);
INSERT OR IGNORE INTO mnt_goals (id, mentee_id, mentor_id, title, progress_pct, due_date, status, sort_order) VALUES ('mg-01', 'mn-ada', 'mentor-1', 'NaijaEats demo day', 90, 'Aug 30', 'on track', 0), ('mg-02', 'mn-ada', 'mentor-1', 'Backend certification', 60, 'Oct 15', 'on track', 1), ('mg-03', 'mn-ada', 'mentor-1', 'Interview readiness', 35, 'Nov 1', 'needs focus', 2), ('mg-04', 'mn-tobi', 'mentor-1', 'CI/CD certification', 55, 'Sep 20', 'on track', 3), ('mg-05', 'mn-zainab', 'mentor-1', 'Portfolio launch', 40, 'Sep 5', 'needs focus', 4), ('mg-06', 'mn-ada', 'mentor-1', 'First internship application', 25, 'Oct 1', 'new', 5);
INSERT OR IGNORE INTO mnt_requests (id, mentor_id, requester_name, track, why, status, sort_order) VALUES ('mr-01', 'mentor-1', 'Hauwa Bello', 'Cloud & DevOps · Cohort 16', 'Wants help planning her AWS certification path.', 'pending', 0), ('mr-02', 'mentor-1', 'Seun Adeleke', 'Full-Stack · Cohort 16', 'Career switcher from civil engineering — needs a roadmap.', 'pending', 1);
INSERT OR IGNORE INTO mnt_availability (id, mentor_id, day, hours, is_open, sort_order) VALUES ('av-01', 'mentor-1', 'Mon', '15:00 – 18:00', 1, 0), ('av-02', 'mentor-1', 'Tue', '15:00 – 18:00', 0, 1), ('av-03', 'mentor-1', 'Wed', '15:00 – 18:00', 1, 2), ('av-04', 'mentor-1', 'Thu', '15:00 – 18:00', 0, 3), ('av-05', 'mentor-1', 'Fri', '15:00 – 18:00', 1, 4), ('av-06', 'mentor-1', 'Sat', '10:00 – 13:00', 1, 5);
INSERT OR IGNORE INTO mnt_resources (id, mentor_id, group_title, items_json, sort_order) VALUES ('res-01', 'mentor-1', 'Session templates', '["Goal review · 45 min","Mock interview · 60 min","Portfolio critique · 30 min"]', 0), ('res-02', 'mentor-1', 'Career toolkit', '["CV rubric v3","Interview question bank (120+)","Salary guide 2026"]', 1), ('res-03', 'mentor-1', 'Learning support', '["SQL exercise pack","Systems design scenarios","Debugging drills"]', 2), ('res-04', 'mentor-1', 'Reports & feedback', '["Progress report template","Endorsement guide","Goal-setting worksheet"]', 3);
INSERT OR IGNORE INTO mnt_portfolio (id, mentee_id, project_name, status, stars, feedback, sort_order) VALUES ('mp-01', 'mn-ada', 'NaijaEats — food delivery API', 'Featured', 5, 'REST API, 40+ endpoints, strong docs', 0), ('mp-02', 'mn-ada', 'BudgetPadi — expense tracker', 'Live', 4, 'Clean PWA, good offline UX', 1), ('mp-03', 'mn-ada', 'ClassBoard — LMS UI', 'In review', 4, 'Design system depth impressive', 2);
INSERT OR IGNORE INTO mnt_skills (id, mentee_id, skill_name, endorsed, sort_order) VALUES ('msk-01', 'mn-ada', 'Database design', 1, 0), ('msk-02', 'mn-ada', 'REST API development', 1, 1), ('msk-03', 'mn-ada', 'System design basics', 0, 2), ('msk-04', 'mn-ada', 'Technical writing', 0, 3);
INSERT OR IGNORE INTO mnt_applications (id, mentee_id, role, company, stage, applied_date, sort_order) VALUES ('map-01', 'mn-ada', 'Junior Backend Engineer', 'Paystack', 'Interview', 'Aug 5', 0), ('map-02', 'mn-ada', 'Backend Intern', 'Kuda', 'Take-home', 'Jul 28', 1), ('map-03', 'mn-ada', 'Software Eng. Trainee', 'Andela', 'Applied', 'Jul 20', 2), ('map-04', 'mn-ada', 'Junior Developer', 'Flutterwave', 'Rejected', 'Jul 12', 3);
INSERT OR IGNORE INTO mnt_conversations (id, mentor_id, name, track, preview, time_label, unread, sort_order) VALUES ('mc-01', 'mentor-1', 'Ada Okafor', 'Backend specialisation', 'Thursday 18:00 works. I''ll send the link.', '14:11', 1, 0), ('mc-02', 'mentor-1', 'Tobi Adeyemi', 'DevOps', 'CI/CD cert material is ready for review', '09:45', 0, 1), ('mc-03', 'mentor-1', 'Zainab Yusuf', 'Product design', 'Portfolio v2 — can we review on Friday?', 'Yesterday', 1, 2), ('mc-04', 'mentor-1', 'Halima Bello', 'Career switch', 'Welcome to the mentorship program!', 'Jul 28', 0, 3);
INSERT OR IGNORE INTO mnt_threads (id, conversation_id, from_label, body, time_label, sort_order) VALUES ('mt-01', 'mc-01', 'You', 'Great mock interview today. Let''s book a goal review for next week.', '10:00', 0), ('mt-02', 'mc-01', 'Ada', 'Thanks! Thursday 18:00 works for me.', '13:30', 1), ('mt-03', 'mc-01', 'You', 'Let''s do a goal review + demo-day checklist then.', '13:45', 2), ('mt-04', 'mc-01', 'Ada', 'Perfect — I''ll send the link before the session.', '14:11', 3);
`;
