-- Seed: operations suite (inventory, branches, facilities, vendors, tasks, workflows).
INSERT OR IGNORE INTO inventory_items (id, name, category, qty, unit, reorder_point, auto_reorder, unit_price, location, sort_order) VALUES ('inv-01', 'Printer toner · HP 62', 'Consumables', 3, 'unit', 5, 1, 35000, 'Ikeja store', 0), ('inv-02', 'A4 paper (reams)', 'Stationery', 48, 'ream', 20, 0, 4500, 'Ikeja store', 1), ('inv-03', 'Laptop charger 65W', 'Equipment', 12, 'unit', 5, 0, 18000, 'Ikeja store', 2), ('inv-04', 'Cafeteria gas (cylinder)', 'Cafeteria', 2, 'cylinder', 3, 1, 48000, 'Block B', 3), ('inv-05', 'Whiteboard markers (box)', 'Stationery', 22, 'box', 8, 0, 6000, 'Ikeja store', 4), ('inv-06', 'Wi-Fi access point', 'Equipment', 6, 'unit', 2, 0, 65000, 'Block A', 5), ('inv-07', 'Generator fuel (litres)', 'Utilities', 140, 'litre', 60, 1, 1100, 'Power room', 6), ('inv-08', 'Fire extinguisher 6kg', 'Safety', 9, 'unit', 3, 0, 24000, 'Block C', 7);
INSERT OR IGNORE INTO purchase_orders (id, vendor, items, amount, eta, status, sort_order) VALUES ('PO-2413', 'OfficeMate', 'Toner + paper', 185000, '2026-08-05', 'open', 0), ('PO-2412', 'GasMaster', 'Cafeteria gas', 96000, '2026-08-07', 'open', 1), ('PO-2411', 'Compton Power', 'Generator servicing', 120000, '2026-07-28', 'delivered', 2);
INSERT OR IGNORE INTO branches (id, name, location, capacity, occupied, staff_onsite, cost_seat_day, status, sort_order) VALUES ('br-01', 'Ikeja HQ', 'Lagos · Main campus', 400, 342, 42, 8200, 'healthy', 0), ('br-02', 'Victoria Island', 'Lagos · Executive center', 150, 118, 28, 9600, 'steady', 1), ('br-03', 'Abeokuta', 'Ogun · Satellite', 120, 64, 12, 11400, 'underused', 2);
INSERT OR IGNORE INTO facility_rooms (id, name, block, seats, next_event, status, sort_order) VALUES ('rm-01', 'Lab 3 · 40 seats', 'Block B', 40, 'DevOps class · 10:00', 'available', 0), ('rm-02', 'Seminar room · 60 seats', 'Block A', 60, 'Workshop · 13:00', 'available', 1), ('rm-03', 'Studio · 24 seats', 'Block C', 24, 'Design sprint · 09:30', 'available', 2), ('rm-04', 'Lab 1 · 32 seats', 'Block A', 32, 'Free', 'available', 3);
INSERT OR IGNORE INTO maintenance_jobs (id, title, detail, status, sort_order) VALUES ('mnt-01', 'AC repair — Lab 2', 'Assigned · today', 'open', 0), ('mnt-02', 'Generator servicing — Block B', 'Scheduled · today 15:00', 'open', 1), ('mnt-03', 'Fire extinguisher inspection', 'Due Aug 12', 'open', 2);
INSERT OR IGNORE INTO vendors (id, name, category, rating, status, sort_order) VALUES ('ven-01', 'OfficeMate', 'Stationery', 4.8, 'active', 0), ('ven-02', 'GasMaster', 'Cafeteria gas', 4.6, 'active', 1), ('ven-03', 'Compton Power', 'Generator servicing', 3.9, 'watch', 2);
INSERT OR IGNORE INTO vendor_contracts (id, title, renews, value_yr, status, sort_order) VALUES ('con-01', 'OfficeMate annual supply', 'Renews Nov 2026', 2400000, 'active', 0), ('con-02', 'GasMaster delivery SLA', 'Renews Sep 2026', 1100000, 'active', 1);
INSERT OR IGNORE INTO ops_tasks (id, title, assignee, detail, done, sort_order) VALUES ('op-01', 'Weekend cleaning rota', 'Facilities team', 'Today · 5/5 done', 1, 0), ('op-02', 'ISP failover test', 'IT support', 'Today · 17:00', 0, 1), ('op-03', 'Store stock count — Block A', 'Store keeper', 'Thu · 08:00', 0, 2), ('op-04', 'Security patrol log review', 'Security lead', 'Fri · 16:00', 0, 3);
INSERT OR IGNORE INTO workflows (id, name, trigger_detail, stats, status, sort_order) VALUES ('wf-01', 'Visitor badge → notify host', 'Trigger: visitor checks in', '38 runs · 0 errors', 'active', 0), ('wf-02', 'Low stock → supplier PO', 'Trigger: SKU below reorder point', '11 runs · 2 approvals', 'active', 1), ('wf-03', 'Room book → AC + lights', 'Trigger: booking confirmed', '9 runs · sync OK', 'active', 2);
