/* Seed wrapper for student-self-data.sql (manual — mirrors the SQL file). */
export const seedStudentSelfSql = String.raw`-- Seed: Student self-service (attendance + portfolio + reports).
INSERT OR IGNORE INTO stu_att_hub (id, metric, value_label, delta, sort_order) VALUES ('sah-hb-01', 'Present', '61', 'of 65 sessions', 1), ('sah-hb-02', 'Late arrivals', '3', 'avg 9m', 2), ('sah-hb-03', 'Excused', '1', 'medical', 3), ('sah-hb-04', 'Unexcused', '0', 'no strikes', 4);
INSERT OR IGNORE INTO stu_records (id, date_label, course, status, sort_order) VALUES ('sah-rd-01', 'Mon, Jul 28', 'Full-Stack Development', 'Present', 1), ('sah-rd-02', 'Thu, Jul 24', 'Cloud & DevOps', 'Present', 2), ('sah-rd-03', 'Wed, Jul 23', 'Product Design', 'Late 12m', 3), ('sah-rd-04', 'Mon, Jul 21', 'Full-Stack Development', 'Present', 4), ('sah-rd-05', 'Thu, Jul 17', 'Cloud & DevOps', 'Excused', 5);
INSERT OR IGNORE INTO stu_policy (id, rule, value_label, sort_order) VALUES ('sah-po-01', '90% minimum per term', 'You: 94%', 1), ('sah-po-02', 'Lates allowed', '3 per term', 2), ('sah-po-03', 'Check-in window', 'QR · 10 min', 3);
INSERT OR IGNORE INTO stu_portfolio_hub (id, metric, value_label, delta, sort_order) VALUES ('sph-hb-01', 'Projects', '3', '2 featured', 1), ('sph-hb-02', 'Skills verified', '11', '16 OSKM skills', 2), ('sph-hb-03', 'CV downloads', '27', 'this month', 3), ('sph-hb-04', 'Profile views', '142', '+38% this week', 4);
INSERT OR IGNORE INTO stu_projects (id, name, detail, tags, featured, sort_order) VALUES ('sph-pj-01', 'NaijaEats — food delivery API', 'REST API + PostgreSQL, 40+ endpoints, rate limiting, Swagger docs.', '["Node.js","PostgreSQL","Docker"]', 1, 1), ('sph-pj-02', 'BudgetPadi — expense tracker', 'PWA with offline mode, charts and bank-format CSV export.', '["React","PWA","Chart.js"]', 1, 2), ('sph-pj-03', 'ClassBoard — LMS dashboard UI', 'Design system and component library in Figma, 60+ components.', '["Figma","Design system","a11y"]', 0, 3);
INSERT OR IGNORE INTO stu_skills (id, name, pct, sort_order) VALUES ('sph-sk-01', 'JavaScript / TypeScript', 92, 1), ('sph-sk-02', 'Node.js & REST APIs', 84, 2), ('sph-sk-03', 'React & Tailwind', 88, 3), ('sph-sk-04', 'Docker & CI/CD', 61, 4);
INSERT OR IGNORE INTO stu_cv (id, filename, sort_order) VALUES ('sph-cv-01', 'CEA_Ada_Okafor_CV.pdf', 1), ('sph-cv-02', 'One-page resume (ATS)', 2);
INSERT OR IGNORE INTO stu_reports_hub (id, metric, value_label, delta, sort_order) VALUES ('srh-hb-01', 'Saved reports', '6', 'shared with 3 roles', 1), ('srh-hb-02', 'Runs this month', '42', 'avg 11 templates', 2), ('srh-hb-03', 'Scheduled', '3', 'weekly delivery', 3), ('srh-hb-04', 'Data sources', '12', 'all modules live', 4);
INSERT OR IGNORE INTO stu_templates (id, name, category, usage, sort_order) VALUES ('sph-tpl-01', 'Attendance summary — by cohort', 'Academics', '14 runs', 1), ('sph-tpl-02', 'Grade distribution — by course', 'Academics', '9 runs', 2), ('sph-tpl-03', 'Revenue by stream (tuition, services)', 'Finance', '11 runs', 3), ('sph-tpl-04', 'Placement outcomes — by cohort', 'Career', '8 runs', 4);
`;
