-- Seed: Supplier dashboard (OfficeMate Ltd) and Partner dashboard (TechHub Ltd).
INSERT OR IGNORE INTO sup_orders (id, supplier_id, ref, items, amount, due_label, status, sort_order) VALUES ('sup-po-01', 'supplier-1', 'PO-2413', 'Toner HP 62 x6, A4 paper x20', 185000, 'Due Aug 5', 'confirmed', 0), ('sup-po-02', 'supplier-1', 'PO-2412', 'Cafeteria gas cylinders x4', 96000, 'Due Aug 7', 'pending confirm', 1), ('sup-po-03', 'supplier-1', 'PO-2408', 'Desk chairs x10', 310000, 'Delivered Jul 24', 'completed', 2), ('sup-po-04', 'supplier-1', 'PO-2405', 'Whiteboard markers x40', 85000, 'Delivered Jul 10', 'completed', 3), ('sup-po-05', 'supplier-1', 'PO-2402', 'Printer drums x3', 132000, 'Delivered Jul 3', 'completed', 4);
INSERT OR IGNORE INTO sup_deliveries (id, supplier_id, po_label, when_label, to_label, status, sort_order) VALUES ('sup-dl-01', 'supplier-1', 'PO-2413 · Toner + paper', 'Aug 5 · 10:00', 'Ikeja HQ · store', 'scheduled', 0), ('sup-dl-02', 'supplier-1', 'PO-2412 · Gas cylinders', 'Aug 7 · 09:00', 'Ikeja HQ · cafeteria', 'scheduled', 1), ('sup-dl-03', 'supplier-1', 'PO-2408 · Chairs', 'Jul 24 · 11:30', 'VI campus', 'delivered', 2), ('sup-dl-04', 'supplier-1', 'PO-2405 · Markers', 'Jul 10 · 14:00', 'Satellite lab', 'delivered', 3);
INSERT OR IGNORE INTO sup_invoices (id, supplier_id, ref, amount, issued_label, paid_label, status, sort_order) VALUES ('sup-inv-01', 'supplier-1', 'INV-8821', 385000, 'Issued Jul 28 · net-30', '', 'awaiting payment', 0), ('sup-inv-02', 'supplier-1', 'INV-8740', 255000, 'Issued Jul 10', 'Paid Jul 29', 'paid', 1), ('sup-inv-03', 'supplier-1', 'INV-8695', 310000, 'Issued Jun 28', 'Paid Jul 15', 'paid', 2), ('sup-inv-04', 'supplier-1', 'INV-8610', 120000, 'Issued Jun 14', 'Paid Jun 28', 'paid', 3);
INSERT OR IGNORE INTO sup_performance (id, supplier_id, metric, value_label, sort_order) VALUES ('sup-pf-01', 'supplier-1', 'Overall', '4.8', 0), ('sup-pf-02', 'supplier-1', 'Delivery on-time', '100%', 1), ('sup-pf-03', 'supplier-1', 'Quality of goods', '4.9 / 5', 2), ('sup-pf-04', 'supplier-1', 'Responsiveness', '4.7 / 5', 3), ('sup-pf-05', 'supplier-1', 'Pricing fairness', '4.6 / 5', 4);
INSERT OR IGNORE INTO sup_certs (id, supplier_id, title, detail, verified, sort_order) VALUES ('sup-crt-01', 'supplier-1', 'CAC registration', 'Verified 2024', 1, 0), ('sup-crt-02', 'supplier-1', 'Quality service cert', 'Renews Jan 2027', 1, 1);
INSERT OR IGNORE INTO sup_conversations (id, supplier_id, name, preview, time_label, unread, sort_order) VALUES ('sup-conv-01', 'supplier-1', 'CEA Procurement', 'Re: PO-2413 delivery window', 'Today 08:40', 1, 0), ('sup-conv-02', 'supplier-1', 'CEA Accounts', 'INV-8821 processing · Jul 31', 'Jul 31', 0, 1), ('sup-conv-03', 'supplier-1', 'CEA Store', 'Chairs received, thanks!', 'Jul 24', 0, 2);
INSERT OR IGNORE INTO sup_threads (id, conversation_id, from_label, body, time_label, sort_order) VALUES ('sup-th-01', 'sup-conv-01', 'CEA Procurement', 'Can we move the PO-2413 delivery to the morning window on Aug 5?', 'Yesterday 16:20', 0), ('sup-th-02', 'sup-conv-01', 'You', 'Yes, 10:00 works for us — confirming now.', 'Yesterday 17:05', 1), ('sup-th-03', 'sup-conv-01', 'CEA Procurement', 'Confirmed. Store will sign for it.', 'Today 08:40', 2);
INSERT OR IGNORE INTO ptn_agreements (id, partner_id, title, detail, status, renew_label, sort_order) VALUES ('ptn-agr-01', 'partner-1', 'Master partnership agreement', 'Signed Feb 2025', 'active', 'renews Feb 2027', 0), ('ptn-agr-02', 'partner-1', 'Revenue share addendum', 'Signed Jan 2026 · 12% share', 'active', '', 1), ('ptn-agr-03', 'partner-1', 'Event co-branding MOU', 'Draft · review by Aug 10', 'draft', '', 2);
INSERT OR IGNORE INTO ptn_collaborations (id, partner_id, title, detail, status, sort_order) VALUES ('ptn-coll-01', 'partner-1', 'Tech Skills Bootcamp', 'Aug 22 · Ikeja HQ', 'scheduled', 0), ('ptn-coll-02', 'partner-1', 'Employer roundtable', 'Sep 10 · VI campus', 'confirmed', 1), ('ptn-coll-03', 'partner-1', 'Hackathon sponsorship', 'Proposal with marketing', 'in discussion', 2);
INSERT OR IGNORE INTO ptn_referrals (id, partner_id, name, status, value_label, sort_order) VALUES ('ptn-ref-01', 'partner-1', 'Tola Bakare', 'Enrolled', '₦120,000', 0), ('ptn-ref-02', 'partner-1', 'Musa Danjuma', 'Applied', 'Pending', 1), ('ptn-ref-03', 'partner-1', 'Ngozi Eze', 'Contacted', '—', 2);
INSERT OR IGNORE INTO ptn_resources (id, partner_id, title, kind, detail, sort_order) VALUES ('ptn-res-01', 'partner-1', 'Co-branded logo kit', 'logo', 'PNG · SVG · 12 assets', 0), ('ptn-res-02', 'partner-1', 'Program flyer templates', 'flyer', 'Figma · 4 sizes', 1), ('ptn-res-03', 'partner-1', 'Partner brand guidelines', 'guidelines', 'PDF · v2.1', 2), ('ptn-res-04', 'partner-1', 'Email banner set', 'banner', 'PNG · 6 variants', 3);
INSERT OR IGNORE INTO ptn_reports (id, partner_id, title, detail, kind, value_label, sort_order) VALUES ('ptn-rep-01', 'partner-1', 'Q3 revenue share statement', 'Aug 2 · PDF', 'revenue-share', '₦1.9m', 0), ('ptn-rep-02', 'partner-1', 'Referral impact report', 'Jul 31 · PDF', 'referral-impact', '₦720k', 1), ('ptn-rep-03', 'partner-1', 'Co-branded event recap', 'Jul 20 · Slides', 'event-recap', '', 2);
INSERT OR IGNORE INTO ptn_conversations (id, partner_id, name, preview, time_label, unread, sort_order) VALUES ('ptn-conv-01', 'partner-1', 'CEA Partnerships team', 'Re: Hackathon sponsorship — sent today', 'Today 09:15', 2, 0), ('ptn-conv-02', 'partner-1', 'Marketing · co-branding', 'New banner set ready — Aug 1', 'Aug 1', 0, 1), ('ptn-conv-03', 'partner-1', 'Ops · procurement', 'PO-2413 confirmation — Jul 29', 'Jul 29', 0, 2);
INSERT OR IGNORE INTO ptn_threads (id, conversation_id, from_label, body, time_label, sort_order) VALUES ('ptn-th-01', 'ptn-conv-01', 'CEA Partnerships team', 'Following up on the hackathon sponsorship — the marketing team has a slot.', 'Yesterday 15:02', 0), ('ptn-th-02', 'ptn-conv-01', 'You', 'Great — sending our one-pager and budget ask today.', 'Yesterday 16:45', 1), ('ptn-th-03', 'ptn-conv-01', 'CEA Partnerships team', 'Received. Sending to the sponsorship committee.', 'Today 09:15', 2);