/**
 * Generates api/seeds/content.sql + api/seeds/content.ts from the canonical
 * collections in ../../src/data/site.ts (engines, programs) — the D1 seed
 * source per plans/BACKEND_PREP_PLAN.md. Run: npm run gen:seed (from api/).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { engines, programs } from "../../src/data/site";

const OUT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..", "seeds");

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''").replace(/\\/g, "\\\\")}'`;
}

function jsonString(value: unknown): string {
  return sqlString(JSON.stringify(value));
}

const statements: string[] = [];

for (const engine of engines) {
  statements.push(
    `INSERT INTO engines (key, name, tagline, description, gradient, text, bullets, sort_order) ` +
      `VALUES (${sqlString(engine.key)}, ${sqlString(engine.name)}, ${sqlString(engine.tagline)}, ` +
      `${sqlString(engine.description)}, ${sqlString(engine.gradient)}, ${sqlString(engine.text)}, ` +
      `${jsonString(engine.bullets)}, ${engines.indexOf(engine)});`,
  );
}

for (const program of programs) {
  statements.push(
    `INSERT INTO programs (slug, title, category, engine_key, level, duration, mode, price, rating, ` +
      `learners, blurb, outcomes, modules, tools) ` +
      `VALUES (${sqlString(program.slug)}, ${sqlString(program.title)}, ${sqlString(program.category)}, ` +
      `${sqlString(program.engine)}, ${sqlString(program.level)}, ${sqlString(program.duration)}, ` +
      `${sqlString(program.mode)}, ${program.price}, ${program.rating}, ${program.learners}, ` +
      `${sqlString(program.blurb)}, ${jsonString(program.outcomes)}, ${jsonString(program.modules)}, ` +
      `${jsonString(program.tools)});`,
  );
}

const sql = statements.join("\n") + "\n";

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(resolve(OUT_DIR, "content.sql"), sql, "utf8");

const tsModule = `/* GENERATED by scripts/gen-seed.ts — do not edit. Re-run: npm run gen:seed */
export const seedContentSql = String.raw\`${sql.replace(/`/g, "\\`").replace(/\$\{/g, "\\${")}\`;
`;

writeFileSync(resolve(OUT_DIR, "content.ts"), tsModule, "utf8");

console.log(`Wrote seeds/content.sql and seeds/content.ts (${statements.length} statements).`);
