/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnginesRouteImport } from './routes/engines'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as WorkRouteImport } from './routes/work'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppGradesRouteImport } from './routes/app/grades'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as ApplyIndexRouteImport } from './routes/apply/index'
import { Route as ApplyStatusRouteImport } from './routes/apply/status'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthMfaRouteImport } from './routes/auth.mfa'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CertificatesVerifyRouteImport } from './routes/certificates.verify'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalAcademicBoardRouteImport } from './routes/portal/academic-board'
import { Route as PortalAccountantRouteImport } from './routes/portal/accountant'
import { Route as PortalAdminRouteImport } from './routes/portal/admin'
import { Route as PortalAdmissionsRouteImport } from './routes/portal/admissions'
import { Route as PortalAlumniRouteImport } from './routes/portal/alumni'
import { Route as PortalCareerServicesRouteImport } from './routes/portal/career-services'
import { Route as PortalClientRouteImport } from './routes/portal/client'
import { Route as PortalDataRouteImport } from './routes/portal/data'
import { Route as PortalDeveloperRouteImport } from './routes/portal/developer'
import { Route as PortalDevopsRouteImport } from './routes/portal/devops'
import { Route as PortalEmployerRouteImport } from './routes/portal/employer'
import { Route as PortalExecutiveRouteImport } from './routes/portal/executive'
import { Route as PortalFinanceRouteImport } from './routes/portal/finance'
import { Route as PortalGovernmentRouteImport } from './routes/portal/government'
import { Route as PortalHrRouteImport } from './routes/portal/hr'
import { Route as PortalInstructorRouteImport } from './routes/portal/instructor'
import { Route as PortalInternRouteImport } from './routes/portal/intern'
import { Route as PortalItSupportRouteImport } from './routes/portal/it-support'
import { Route as PortalMarketingRouteImport } from './routes/portal/marketing'
import { Route as PortalMentorRouteImport } from './routes/portal/mentor'
import { Route as PortalNgoRouteImport } from './routes/portal/ngo'
import { Route as PortalOperationsRouteImport } from './routes/portal/operations'
import { Route as PortalParentRouteImport } from './routes/portal/parent'
import { Route as PortalPartnerRouteImport } from './routes/portal/partner'
import { Route as PortalQualityRouteImport } from './routes/portal/quality'
import { Route as PortalReceptionistRouteImport } from './routes/portal/receptionist'
import { Route as PortalRegistrarRouteImport } from './routes/portal/registrar'
import { Route as PortalSecurityRouteImport } from './routes/portal/security'
import { Route as PortalStudentRouteImport } from './routes/portal/student'
import { Route as PortalSupplierRouteImport } from './routes/portal/supplier'
import { Route as PortalVolunteerRouteImport } from './routes/portal/volunteer'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as ProgramsCompareRouteImport } from './routes/programs/compare'
import { Route as AppAssessmentsIndexRouteImport } from './routes/app/assessments/index'
import { Route as AppAssignmentsIndexRouteImport } from './routes/app/assignments/index'
import { Route as AppAssignmentsAssignmentIdRouteImport } from './routes/app/assignments/$assignmentId'
import { Route as AppInstructorAnalyticsRouteImport } from './routes/app/instructor/analytics'
import { Route as AppInstructorAttendanceRouteImport } from './routes/app/instructor/attendance'
import { Route as AppInstructorGradebookRouteImport } from './routes/app/instructor/gradebook'
import { Route as AppLearnIndexRouteImport } from './routes/app/learn/index'
import { Route as AppLearnCourseIdRouteImport } from './routes/app/learn/$courseId'
import { Route as AppAssessmentsAssessmentIdTakeRouteImport } from './routes/app/assessments/$assessmentId/take'
import { Route as AppInstructorAssignmentsIndexRouteImport } from './routes/app/instructor/assignments/index'
import { Route as AppInstructorCoursesCourseIdRouteImport } from './routes/app/instructor/courses/$courseId'
import { Route as AppInstructorAssignmentsSubmissionIdGradeRouteImport } from './routes/app/instructor/assignments/$submissionId.grade'
import { Route as AppLearnCourseIdLessonsLessonIdRouteImport } from './routes/app/learn/$courseId.lessons.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesRoute = EnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/app/calendar',
  path: '/app/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/app/grades',
  path: '/app/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/app/messages',
  path: '/app/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyStatusRoute = ApplyStatusRouteImport.update({
  id: '/apply/status',
  path: '/apply/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/auth/mfa',
  path: '/auth/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesVerifyRoute = CertificatesVerifyRouteImport.update({
  id: '/certificates/verify',
  path: '/certificates/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAcademicBoardRoute = PortalAcademicBoardRouteImport.update({
  id: '/portal/academic-board',
  path: '/portal/academic-board',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAccountantRoute = PortalAccountantRouteImport.update({
  id: '/portal/accountant',
  path: '/portal/accountant',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/portal/admin',
  path: '/portal/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdmissionsRoute = PortalAdmissionsRouteImport.update({
  id: '/portal/admissions',
  path: '/portal/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlumniRoute = PortalAlumniRouteImport.update({
  id: '/portal/alumni',
  path: '/portal/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCareerServicesRoute = PortalCareerServicesRouteImport.update({
  id: '/portal/career-services',
  path: '/portal/career-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalClientRoute = PortalClientRouteImport.update({
  id: '/portal/client',
  path: '/portal/client',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDataRoute = PortalDataRouteImport.update({
  id: '/portal/data',
  path: '/portal/data',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDeveloperRoute = PortalDeveloperRouteImport.update({
  id: '/portal/developer',
  path: '/portal/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDevopsRoute = PortalDevopsRouteImport.update({
  id: '/portal/devops',
  path: '/portal/devops',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEmployerRoute = PortalEmployerRouteImport.update({
  id: '/portal/employer',
  path: '/portal/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalExecutiveRoute = PortalExecutiveRouteImport.update({
  id: '/portal/executive',
  path: '/portal/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalFinanceRoute = PortalFinanceRouteImport.update({
  id: '/portal/finance',
  path: '/portal/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalGovernmentRoute = PortalGovernmentRouteImport.update({
  id: '/portal/government',
  path: '/portal/government',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalHrRoute = PortalHrRouteImport.update({
  id: '/portal/hr',
  path: '/portal/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInstructorRoute = PortalInstructorRouteImport.update({
  id: '/portal/instructor',
  path: '/portal/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInternRoute = PortalInternRouteImport.update({
  id: '/portal/intern',
  path: '/portal/intern',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalItSupportRoute = PortalItSupportRouteImport.update({
  id: '/portal/it-support',
  path: '/portal/it-support',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMarketingRoute = PortalMarketingRouteImport.update({
  id: '/portal/marketing',
  path: '/portal/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMentorRoute = PortalMentorRouteImport.update({
  id: '/portal/mentor',
  path: '/portal/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNgoRoute = PortalNgoRouteImport.update({
  id: '/portal/ngo',
  path: '/portal/ngo',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalOperationsRoute = PortalOperationsRouteImport.update({
  id: '/portal/operations',
  path: '/portal/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalParentRoute = PortalParentRouteImport.update({
  id: '/portal/parent',
  path: '/portal/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPartnerRoute = PortalPartnerRouteImport.update({
  id: '/portal/partner',
  path: '/portal/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalQualityRoute = PortalQualityRouteImport.update({
  id: '/portal/quality',
  path: '/portal/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalReceptionistRoute = PortalReceptionistRouteImport.update({
  id: '/portal/receptionist',
  path: '/portal/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRegistrarRoute = PortalRegistrarRouteImport.update({
  id: '/portal/registrar',
  path: '/portal/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSecurityRoute = PortalSecurityRouteImport.update({
  id: '/portal/security',
  path: '/portal/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalStudentRoute = PortalStudentRouteImport.update({
  id: '/portal/student',
  path: '/portal/student',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSupplierRoute = PortalSupplierRouteImport.update({
  id: '/portal/supplier',
  path: '/portal/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalVolunteerRoute = PortalVolunteerRouteImport.update({
  id: '/portal/volunteer',
  path: '/portal/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsCompareRoute = ProgramsCompareRouteImport.update({
  id: '/programs/compare',
  path: '/programs/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssessmentsIndexRoute = AppAssessmentsIndexRouteImport.update({
  id: '/app/assessments/',
  path: '/app/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssignmentsIndexRoute = AppAssignmentsIndexRouteImport.update({
  id: '/app/assignments/',
  path: '/app/assignments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssignmentsAssignmentIdRoute =
  AppAssignmentsAssignmentIdRouteImport.update({
    id: '/app/assignments/$assignmentId',
    path: '/app/assignments/$assignmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppInstructorAnalyticsRoute = AppInstructorAnalyticsRouteImport.update({
  id: '/app/instructor/analytics',
  path: '/app/instructor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInstructorAttendanceRoute = AppInstructorAttendanceRouteImport.update({
  id: '/app/instructor/attendance',
  path: '/app/instructor/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInstructorGradebookRoute = AppInstructorGradebookRouteImport.update({
  id: '/app/instructor/gradebook',
  path: '/app/instructor/gradebook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLearnIndexRoute = AppLearnIndexRouteImport.update({
  id: '/app/learn/',
  path: '/app/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLearnCourseIdRoute = AppLearnCourseIdRouteImport.update({
  id: '/app/learn/$courseId',
  path: '/app/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssessmentsAssessmentIdTakeRoute =
  AppAssessmentsAssessmentIdTakeRouteImport.update({
    id: '/app/assessments/$assessmentId/take',
    path: '/app/assessments/$assessmentId/take',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppInstructorAssignmentsIndexRoute =
  AppInstructorAssignmentsIndexRouteImport.update({
    id: '/app/instructor/assignments/',
    path: '/app/instructor/assignments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppInstructorCoursesCourseIdRoute =
  AppInstructorCoursesCourseIdRouteImport.update({
    id: '/app/instructor/courses/$courseId',
    path: '/app/instructor/courses/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppInstructorAssignmentsSubmissionIdGradeRoute =
  AppInstructorAssignmentsSubmissionIdGradeRouteImport.update({
    id: '/app/instructor/assignments/$submissionId/grade',
    path: '/app/instructor/assignments/$submissionId/grade',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppLearnCourseIdLessonsLessonIdRoute =
  AppLearnCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AppLearnCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/engines': typeof EnginesRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/marketplace': typeof MarketplaceRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/stories': typeof StoriesRoute
  '/visit': typeof VisitRoute
  '/work': typeof WorkRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/grades': typeof AppGradesRoute
  '/app/messages': typeof AppMessagesRoute
  '/apply/status': typeof ApplyStatusRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificates/verify': typeof CertificatesVerifyRoute
  '/portal/academic-board': typeof PortalAcademicBoardRoute
  '/portal/accountant': typeof PortalAccountantRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/admissions': typeof PortalAdmissionsRoute
  '/portal/alumni': typeof PortalAlumniRoute
  '/portal/career-services': typeof PortalCareerServicesRoute
  '/portal/client': typeof PortalClientRoute
  '/portal/data': typeof PortalDataRoute
  '/portal/developer': typeof PortalDeveloperRoute
  '/portal/devops': typeof PortalDevopsRoute
  '/portal/employer': typeof PortalEmployerRoute
  '/portal/executive': typeof PortalExecutiveRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/government': typeof PortalGovernmentRoute
  '/portal/hr': typeof PortalHrRoute
  '/portal/instructor': typeof PortalInstructorRoute
  '/portal/intern': typeof PortalInternRoute
  '/portal/it-support': typeof PortalItSupportRoute
  '/portal/marketing': typeof PortalMarketingRoute
  '/portal/mentor': typeof PortalMentorRoute
  '/portal/ngo': typeof PortalNgoRoute
  '/portal/operations': typeof PortalOperationsRoute
  '/portal/parent': typeof PortalParentRoute
  '/portal/partner': typeof PortalPartnerRoute
  '/portal/quality': typeof PortalQualityRoute
  '/portal/receptionist': typeof PortalReceptionistRoute
  '/portal/registrar': typeof PortalRegistrarRoute
  '/portal/security': typeof PortalSecurityRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/supplier': typeof PortalSupplierRoute
  '/portal/volunteer': typeof PortalVolunteerRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/compare': typeof ProgramsCompareRoute
  '/app/': typeof AppIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/app/assignments/$assignmentId': typeof AppAssignmentsAssignmentIdRoute
  '/app/instructor/analytics': typeof AppInstructorAnalyticsRoute
  '/app/instructor/attendance': typeof AppInstructorAttendanceRoute
  '/app/instructor/gradebook': typeof AppInstructorGradebookRoute
  '/app/learn/$courseId': typeof AppLearnCourseIdRouteWithChildren
  '/app/assessments/': typeof AppAssessmentsIndexRoute
  '/app/assignments/': typeof AppAssignmentsIndexRoute
  '/app/learn/': typeof AppLearnIndexRoute
  '/app/assessments/$assessmentId/take': typeof AppAssessmentsAssessmentIdTakeRoute
  '/app/instructor/courses/$courseId': typeof AppInstructorCoursesCourseIdRoute
  '/app/instructor/assignments/': typeof AppInstructorAssignmentsIndexRoute
  '/app/instructor/assignments/$submissionId/grade': typeof AppInstructorAssignmentsSubmissionIdGradeRoute
  '/app/learn/$courseId/lessons/$lessonId': typeof AppLearnCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/engines': typeof EnginesRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/marketplace': typeof MarketplaceRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/stories': typeof StoriesRoute
  '/visit': typeof VisitRoute
  '/work': typeof WorkRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/grades': typeof AppGradesRoute
  '/app/messages': typeof AppMessagesRoute
  '/apply/status': typeof ApplyStatusRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificates/verify': typeof CertificatesVerifyRoute
  '/portal/academic-board': typeof PortalAcademicBoardRoute
  '/portal/accountant': typeof PortalAccountantRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/admissions': typeof PortalAdmissionsRoute
  '/portal/alumni': typeof PortalAlumniRoute
  '/portal/career-services': typeof PortalCareerServicesRoute
  '/portal/client': typeof PortalClientRoute
  '/portal/data': typeof PortalDataRoute
  '/portal/developer': typeof PortalDeveloperRoute
  '/portal/devops': typeof PortalDevopsRoute
  '/portal/employer': typeof PortalEmployerRoute
  '/portal/executive': typeof PortalExecutiveRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/government': typeof PortalGovernmentRoute
  '/portal/hr': typeof PortalHrRoute
  '/portal/instructor': typeof PortalInstructorRoute
  '/portal/intern': typeof PortalInternRoute
  '/portal/it-support': typeof PortalItSupportRoute
  '/portal/marketing': typeof PortalMarketingRoute
  '/portal/mentor': typeof PortalMentorRoute
  '/portal/ngo': typeof PortalNgoRoute
  '/portal/operations': typeof PortalOperationsRoute
  '/portal/parent': typeof PortalParentRoute
  '/portal/partner': typeof PortalPartnerRoute
  '/portal/quality': typeof PortalQualityRoute
  '/portal/receptionist': typeof PortalReceptionistRoute
  '/portal/registrar': typeof PortalRegistrarRoute
  '/portal/security': typeof PortalSecurityRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/supplier': typeof PortalSupplierRoute
  '/portal/volunteer': typeof PortalVolunteerRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/compare': typeof ProgramsCompareRoute
  '/app': typeof AppIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/blog': typeof BlogIndexRoute
  '/portal': typeof PortalIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/app/assignments/$assignmentId': typeof AppAssignmentsAssignmentIdRoute
  '/app/instructor/analytics': typeof AppInstructorAnalyticsRoute
  '/app/instructor/attendance': typeof AppInstructorAttendanceRoute
  '/app/instructor/gradebook': typeof AppInstructorGradebookRoute
  '/app/learn/$courseId': typeof AppLearnCourseIdRouteWithChildren
  '/app/assessments': typeof AppAssessmentsIndexRoute
  '/app/assignments': typeof AppAssignmentsIndexRoute
  '/app/learn': typeof AppLearnIndexRoute
  '/app/assessments/$assessmentId/take': typeof AppAssessmentsAssessmentIdTakeRoute
  '/app/instructor/courses/$courseId': typeof AppInstructorCoursesCourseIdRoute
  '/app/instructor/assignments': typeof AppInstructorAssignmentsIndexRoute
  '/app/instructor/assignments/$submissionId/grade': typeof AppInstructorAssignmentsSubmissionIdGradeRoute
  '/app/learn/$courseId/lessons/$lessonId': typeof AppLearnCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/alumni': typeof AlumniRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/engines': typeof EnginesRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/marketplace': typeof MarketplaceRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/stories': typeof StoriesRoute
  '/visit': typeof VisitRoute
  '/work': typeof WorkRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/grades': typeof AppGradesRoute
  '/app/messages': typeof AppMessagesRoute
  '/apply/status': typeof ApplyStatusRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificates/verify': typeof CertificatesVerifyRoute
  '/portal/academic-board': typeof PortalAcademicBoardRoute
  '/portal/accountant': typeof PortalAccountantRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/admissions': typeof PortalAdmissionsRoute
  '/portal/alumni': typeof PortalAlumniRoute
  '/portal/career-services': typeof PortalCareerServicesRoute
  '/portal/client': typeof PortalClientRoute
  '/portal/data': typeof PortalDataRoute
  '/portal/developer': typeof PortalDeveloperRoute
  '/portal/devops': typeof PortalDevopsRoute
  '/portal/employer': typeof PortalEmployerRoute
  '/portal/executive': typeof PortalExecutiveRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/government': typeof PortalGovernmentRoute
  '/portal/hr': typeof PortalHrRoute
  '/portal/instructor': typeof PortalInstructorRoute
  '/portal/intern': typeof PortalInternRoute
  '/portal/it-support': typeof PortalItSupportRoute
  '/portal/marketing': typeof PortalMarketingRoute
  '/portal/mentor': typeof PortalMentorRoute
  '/portal/ngo': typeof PortalNgoRoute
  '/portal/operations': typeof PortalOperationsRoute
  '/portal/parent': typeof PortalParentRoute
  '/portal/partner': typeof PortalPartnerRoute
  '/portal/quality': typeof PortalQualityRoute
  '/portal/receptionist': typeof PortalReceptionistRoute
  '/portal/registrar': typeof PortalRegistrarRoute
  '/portal/security': typeof PortalSecurityRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/supplier': typeof PortalSupplierRoute
  '/portal/volunteer': typeof PortalVolunteerRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/compare': typeof ProgramsCompareRoute
  '/app/': typeof AppIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/app/assignments/$assignmentId': typeof AppAssignmentsAssignmentIdRoute
  '/app/instructor/analytics': typeof AppInstructorAnalyticsRoute
  '/app/instructor/attendance': typeof AppInstructorAttendanceRoute
  '/app/instructor/gradebook': typeof AppInstructorGradebookRoute
  '/app/learn/$courseId': typeof AppLearnCourseIdRouteWithChildren
  '/app/assessments/': typeof AppAssessmentsIndexRoute
  '/app/assignments/': typeof AppAssignmentsIndexRoute
  '/app/learn/': typeof AppLearnIndexRoute
  '/app/assessments/$assessmentId/take': typeof AppAssessmentsAssessmentIdTakeRoute
  '/app/instructor/courses/$courseId': typeof AppInstructorCoursesCourseIdRoute
  '/app/instructor/assignments/': typeof AppInstructorAssignmentsIndexRoute
  '/app/instructor/assignments/$submissionId/grade': typeof AppInstructorAssignmentsSubmissionIdGradeRoute
  '/app/learn/$courseId/lessons/$lessonId': typeof AppLearnCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/alumni'
    | '/careers'
    | '/community'
    | '/contact'
    | '/engines'
    | '/events'
    | '/faq'
    | '/marketplace'
    | '/partners'
    | '/pricing'
    | '/scholarships'
    | '/services'
    | '/stories'
    | '/visit'
    | '/work'
    | '/app/calendar'
    | '/app/grades'
    | '/app/messages'
    | '/apply/status'
    | '/auth/forgot-password'
    | '/auth/mfa'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/certificates/verify'
    | '/portal/academic-board'
    | '/portal/accountant'
    | '/portal/admin'
    | '/portal/admissions'
    | '/portal/alumni'
    | '/portal/career-services'
    | '/portal/client'
    | '/portal/data'
    | '/portal/developer'
    | '/portal/devops'
    | '/portal/employer'
    | '/portal/executive'
    | '/portal/finance'
    | '/portal/government'
    | '/portal/hr'
    | '/portal/instructor'
    | '/portal/intern'
    | '/portal/it-support'
    | '/portal/marketing'
    | '/portal/mentor'
    | '/portal/ngo'
    | '/portal/operations'
    | '/portal/parent'
    | '/portal/partner'
    | '/portal/quality'
    | '/portal/receptionist'
    | '/portal/registrar'
    | '/portal/security'
    | '/portal/student'
    | '/portal/supplier'
    | '/portal/volunteer'
    | '/programs/$slug'
    | '/programs/compare'
    | '/app/'
    | '/apply/'
    | '/blog/'
    | '/portal/'
    | '/programs/'
    | '/app/assignments/$assignmentId'
    | '/app/instructor/analytics'
    | '/app/instructor/attendance'
    | '/app/instructor/gradebook'
    | '/app/learn/$courseId'
    | '/app/assessments/'
    | '/app/assignments/'
    | '/app/learn/'
    | '/app/assessments/$assessmentId/take'
    | '/app/instructor/courses/$courseId'
    | '/app/instructor/assignments/'
    | '/app/instructor/assignments/$submissionId/grade'
    | '/app/learn/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/alumni'
    | '/careers'
    | '/community'
    | '/contact'
    | '/engines'
    | '/events'
    | '/faq'
    | '/marketplace'
    | '/partners'
    | '/pricing'
    | '/scholarships'
    | '/services'
    | '/stories'
    | '/visit'
    | '/work'
    | '/app/calendar'
    | '/app/grades'
    | '/app/messages'
    | '/apply/status'
    | '/auth/forgot-password'
    | '/auth/mfa'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/certificates/verify'
    | '/portal/academic-board'
    | '/portal/accountant'
    | '/portal/admin'
    | '/portal/admissions'
    | '/portal/alumni'
    | '/portal/career-services'
    | '/portal/client'
    | '/portal/data'
    | '/portal/developer'
    | '/portal/devops'
    | '/portal/employer'
    | '/portal/executive'
    | '/portal/finance'
    | '/portal/government'
    | '/portal/hr'
    | '/portal/instructor'
    | '/portal/intern'
    | '/portal/it-support'
    | '/portal/marketing'
    | '/portal/mentor'
    | '/portal/ngo'
    | '/portal/operations'
    | '/portal/parent'
    | '/portal/partner'
    | '/portal/quality'
    | '/portal/receptionist'
    | '/portal/registrar'
    | '/portal/security'
    | '/portal/student'
    | '/portal/supplier'
    | '/portal/volunteer'
    | '/programs/$slug'
    | '/programs/compare'
    | '/app'
    | '/apply'
    | '/blog'
    | '/portal'
    | '/programs'
    | '/app/assignments/$assignmentId'
    | '/app/instructor/analytics'
    | '/app/instructor/attendance'
    | '/app/instructor/gradebook'
    | '/app/learn/$courseId'
    | '/app/assessments'
    | '/app/assignments'
    | '/app/learn'
    | '/app/assessments/$assessmentId/take'
    | '/app/instructor/courses/$courseId'
    | '/app/instructor/assignments'
    | '/app/instructor/assignments/$submissionId/grade'
    | '/app/learn/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/alumni'
    | '/careers'
    | '/community'
    | '/contact'
    | '/engines'
    | '/events'
    | '/faq'
    | '/marketplace'
    | '/partners'
    | '/pricing'
    | '/scholarships'
    | '/services'
    | '/stories'
    | '/visit'
    | '/work'
    | '/app/calendar'
    | '/app/grades'
    | '/app/messages'
    | '/apply/status'
    | '/auth/forgot-password'
    | '/auth/mfa'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/certificates/verify'
    | '/portal/academic-board'
    | '/portal/accountant'
    | '/portal/admin'
    | '/portal/admissions'
    | '/portal/alumni'
    | '/portal/career-services'
    | '/portal/client'
    | '/portal/data'
    | '/portal/developer'
    | '/portal/devops'
    | '/portal/employer'
    | '/portal/executive'
    | '/portal/finance'
    | '/portal/government'
    | '/portal/hr'
    | '/portal/instructor'
    | '/portal/intern'
    | '/portal/it-support'
    | '/portal/marketing'
    | '/portal/mentor'
    | '/portal/ngo'
    | '/portal/operations'
    | '/portal/parent'
    | '/portal/partner'
    | '/portal/quality'
    | '/portal/receptionist'
    | '/portal/registrar'
    | '/portal/security'
    | '/portal/student'
    | '/portal/supplier'
    | '/portal/volunteer'
    | '/programs/$slug'
    | '/programs/compare'
    | '/app/'
    | '/apply/'
    | '/blog/'
    | '/portal/'
    | '/programs/'
    | '/app/assignments/$assignmentId'
    | '/app/instructor/analytics'
    | '/app/instructor/attendance'
    | '/app/instructor/gradebook'
    | '/app/learn/$courseId'
    | '/app/assessments/'
    | '/app/assignments/'
    | '/app/learn/'
    | '/app/assessments/$assessmentId/take'
    | '/app/instructor/courses/$courseId'
    | '/app/instructor/assignments/'
    | '/app/instructor/assignments/$submissionId/grade'
    | '/app/learn/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AlumniRoute: typeof AlumniRoute
  CareersRoute: typeof CareersRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EnginesRoute: typeof EnginesRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  ServicesRoute: typeof ServicesRoute
  StoriesRoute: typeof StoriesRoute
  VisitRoute: typeof VisitRoute
  WorkRoute: typeof WorkRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppGradesRoute: typeof AppGradesRoute
  AppMessagesRoute: typeof AppMessagesRoute
  ApplyStatusRoute: typeof ApplyStatusRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CertificatesVerifyRoute: typeof CertificatesVerifyRoute
  PortalAcademicBoardRoute: typeof PortalAcademicBoardRoute
  PortalAccountantRoute: typeof PortalAccountantRoute
  PortalAdminRoute: typeof PortalAdminRoute
  PortalAdmissionsRoute: typeof PortalAdmissionsRoute
  PortalAlumniRoute: typeof PortalAlumniRoute
  PortalCareerServicesRoute: typeof PortalCareerServicesRoute
  PortalClientRoute: typeof PortalClientRoute
  PortalDataRoute: typeof PortalDataRoute
  PortalDeveloperRoute: typeof PortalDeveloperRoute
  PortalDevopsRoute: typeof PortalDevopsRoute
  PortalEmployerRoute: typeof PortalEmployerRoute
  PortalExecutiveRoute: typeof PortalExecutiveRoute
  PortalFinanceRoute: typeof PortalFinanceRoute
  PortalGovernmentRoute: typeof PortalGovernmentRoute
  PortalHrRoute: typeof PortalHrRoute
  PortalInstructorRoute: typeof PortalInstructorRoute
  PortalInternRoute: typeof PortalInternRoute
  PortalItSupportRoute: typeof PortalItSupportRoute
  PortalMarketingRoute: typeof PortalMarketingRoute
  PortalMentorRoute: typeof PortalMentorRoute
  PortalNgoRoute: typeof PortalNgoRoute
  PortalOperationsRoute: typeof PortalOperationsRoute
  PortalParentRoute: typeof PortalParentRoute
  PortalPartnerRoute: typeof PortalPartnerRoute
  PortalQualityRoute: typeof PortalQualityRoute
  PortalReceptionistRoute: typeof PortalReceptionistRoute
  PortalRegistrarRoute: typeof PortalRegistrarRoute
  PortalSecurityRoute: typeof PortalSecurityRoute
  PortalStudentRoute: typeof PortalStudentRoute
  PortalSupplierRoute: typeof PortalSupplierRoute
  PortalVolunteerRoute: typeof PortalVolunteerRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsCompareRoute: typeof ProgramsCompareRoute
  AppIndexRoute: typeof AppIndexRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  AppAssignmentsAssignmentIdRoute: typeof AppAssignmentsAssignmentIdRoute
  AppInstructorAnalyticsRoute: typeof AppInstructorAnalyticsRoute
  AppInstructorAttendanceRoute: typeof AppInstructorAttendanceRoute
  AppInstructorGradebookRoute: typeof AppInstructorGradebookRoute
  AppLearnCourseIdRoute: typeof AppLearnCourseIdRouteWithChildren
  AppAssessmentsIndexRoute: typeof AppAssessmentsIndexRoute
  AppAssignmentsIndexRoute: typeof AppAssignmentsIndexRoute
  AppLearnIndexRoute: typeof AppLearnIndexRoute
  AppAssessmentsAssessmentIdTakeRoute: typeof AppAssessmentsAssessmentIdTakeRoute
  AppInstructorCoursesCourseIdRoute: typeof AppInstructorCoursesCourseIdRoute
  AppInstructorAssignmentsIndexRoute: typeof AppInstructorAssignmentsIndexRoute
  AppInstructorAssignmentsSubmissionIdGradeRoute: typeof AppInstructorAssignmentsSubmissionIdGradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines': {
      id: '/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof EnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/app/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/grades': {
      id: '/app/grades'
      path: '/app/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/app/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/status': {
      id: '/apply/status'
      path: '/apply/status'
      fullPath: '/apply/status'
      preLoaderRoute: typeof ApplyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/auth/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/verify': {
      id: '/certificates/verify'
      path: '/certificates/verify'
      fullPath: '/certificates/verify'
      preLoaderRoute: typeof CertificatesVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/academic-board': {
      id: '/portal/academic-board'
      path: '/portal/academic-board'
      fullPath: '/portal/academic-board'
      preLoaderRoute: typeof PortalAcademicBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/accountant': {
      id: '/portal/accountant'
      path: '/portal/accountant'
      fullPath: '/portal/accountant'
      preLoaderRoute: typeof PortalAccountantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/portal/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/admissions': {
      id: '/portal/admissions'
      path: '/portal/admissions'
      fullPath: '/portal/admissions'
      preLoaderRoute: typeof PortalAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/alumni': {
      id: '/portal/alumni'
      path: '/portal/alumni'
      fullPath: '/portal/alumni'
      preLoaderRoute: typeof PortalAlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/career-services': {
      id: '/portal/career-services'
      path: '/portal/career-services'
      fullPath: '/portal/career-services'
      preLoaderRoute: typeof PortalCareerServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/client': {
      id: '/portal/client'
      path: '/portal/client'
      fullPath: '/portal/client'
      preLoaderRoute: typeof PortalClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/data': {
      id: '/portal/data'
      path: '/portal/data'
      fullPath: '/portal/data'
      preLoaderRoute: typeof PortalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/developer': {
      id: '/portal/developer'
      path: '/portal/developer'
      fullPath: '/portal/developer'
      preLoaderRoute: typeof PortalDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/devops': {
      id: '/portal/devops'
      path: '/portal/devops'
      fullPath: '/portal/devops'
      preLoaderRoute: typeof PortalDevopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/employer': {
      id: '/portal/employer'
      path: '/portal/employer'
      fullPath: '/portal/employer'
      preLoaderRoute: typeof PortalEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/executive': {
      id: '/portal/executive'
      path: '/portal/executive'
      fullPath: '/portal/executive'
      preLoaderRoute: typeof PortalExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/finance': {
      id: '/portal/finance'
      path: '/portal/finance'
      fullPath: '/portal/finance'
      preLoaderRoute: typeof PortalFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/government': {
      id: '/portal/government'
      path: '/portal/government'
      fullPath: '/portal/government'
      preLoaderRoute: typeof PortalGovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/hr': {
      id: '/portal/hr'
      path: '/portal/hr'
      fullPath: '/portal/hr'
      preLoaderRoute: typeof PortalHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/instructor': {
      id: '/portal/instructor'
      path: '/portal/instructor'
      fullPath: '/portal/instructor'
      preLoaderRoute: typeof PortalInstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/intern': {
      id: '/portal/intern'
      path: '/portal/intern'
      fullPath: '/portal/intern'
      preLoaderRoute: typeof PortalInternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/it-support': {
      id: '/portal/it-support'
      path: '/portal/it-support'
      fullPath: '/portal/it-support'
      preLoaderRoute: typeof PortalItSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/marketing': {
      id: '/portal/marketing'
      path: '/portal/marketing'
      fullPath: '/portal/marketing'
      preLoaderRoute: typeof PortalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/mentor': {
      id: '/portal/mentor'
      path: '/portal/mentor'
      fullPath: '/portal/mentor'
      preLoaderRoute: typeof PortalMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/ngo': {
      id: '/portal/ngo'
      path: '/portal/ngo'
      fullPath: '/portal/ngo'
      preLoaderRoute: typeof PortalNgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/operations': {
      id: '/portal/operations'
      path: '/portal/operations'
      fullPath: '/portal/operations'
      preLoaderRoute: typeof PortalOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/parent': {
      id: '/portal/parent'
      path: '/portal/parent'
      fullPath: '/portal/parent'
      preLoaderRoute: typeof PortalParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/partner': {
      id: '/portal/partner'
      path: '/portal/partner'
      fullPath: '/portal/partner'
      preLoaderRoute: typeof PortalPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/quality': {
      id: '/portal/quality'
      path: '/portal/quality'
      fullPath: '/portal/quality'
      preLoaderRoute: typeof PortalQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/receptionist': {
      id: '/portal/receptionist'
      path: '/portal/receptionist'
      fullPath: '/portal/receptionist'
      preLoaderRoute: typeof PortalReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/registrar': {
      id: '/portal/registrar'
      path: '/portal/registrar'
      fullPath: '/portal/registrar'
      preLoaderRoute: typeof PortalRegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/security': {
      id: '/portal/security'
      path: '/portal/security'
      fullPath: '/portal/security'
      preLoaderRoute: typeof PortalSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/student': {
      id: '/portal/student'
      path: '/portal/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof PortalStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/supplier': {
      id: '/portal/supplier'
      path: '/portal/supplier'
      fullPath: '/portal/supplier'
      preLoaderRoute: typeof PortalSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/volunteer': {
      id: '/portal/volunteer'
      path: '/portal/volunteer'
      fullPath: '/portal/volunteer'
      preLoaderRoute: typeof PortalVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/compare': {
      id: '/programs/compare'
      path: '/programs/compare'
      fullPath: '/programs/compare'
      preLoaderRoute: typeof ProgramsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assessments/': {
      id: '/app/assessments/'
      path: '/app/assessments'
      fullPath: '/app/assessments/'
      preLoaderRoute: typeof AppAssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assignments/': {
      id: '/app/assignments/'
      path: '/app/assignments'
      fullPath: '/app/assignments/'
      preLoaderRoute: typeof AppAssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assignments/$assignmentId': {
      id: '/app/assignments/$assignmentId'
      path: '/app/assignments/$assignmentId'
      fullPath: '/app/assignments/$assignmentId'
      preLoaderRoute: typeof AppAssignmentsAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/instructor/analytics': {
      id: '/app/instructor/analytics'
      path: '/app/instructor/analytics'
      fullPath: '/app/instructor/analytics'
      preLoaderRoute: typeof AppInstructorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/instructor/attendance': {
      id: '/app/instructor/attendance'
      path: '/app/instructor/attendance'
      fullPath: '/app/instructor/attendance'
      preLoaderRoute: typeof AppInstructorAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/instructor/gradebook': {
      id: '/app/instructor/gradebook'
      path: '/app/instructor/gradebook'
      fullPath: '/app/instructor/gradebook'
      preLoaderRoute: typeof AppInstructorGradebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/learn/': {
      id: '/app/learn/'
      path: '/app/learn'
      fullPath: '/app/learn/'
      preLoaderRoute: typeof AppLearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/learn/$courseId': {
      id: '/app/learn/$courseId'
      path: '/app/learn/$courseId'
      fullPath: '/app/learn/$courseId'
      preLoaderRoute: typeof AppLearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assessments/$assessmentId/take': {
      id: '/app/assessments/$assessmentId/take'
      path: '/app/assessments/$assessmentId/take'
      fullPath: '/app/assessments/$assessmentId/take'
      preLoaderRoute: typeof AppAssessmentsAssessmentIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/instructor/assignments/': {
      id: '/app/instructor/assignments/'
      path: '/app/instructor/assignments'
      fullPath: '/app/instructor/assignments/'
      preLoaderRoute: typeof AppInstructorAssignmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/instructor/courses/$courseId': {
      id: '/app/instructor/courses/$courseId'
      path: '/app/instructor/courses/$courseId'
      fullPath: '/app/instructor/courses/$courseId'
      preLoaderRoute: typeof AppInstructorCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/instructor/assignments/$submissionId/grade': {
      id: '/app/instructor/assignments/$submissionId/grade'
      path: '/app/instructor/assignments/$submissionId/grade'
      fullPath: '/app/instructor/assignments/$submissionId/grade'
      preLoaderRoute: typeof AppInstructorAssignmentsSubmissionIdGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/learn/$courseId/lessons/$lessonId': {
      id: '/app/learn/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/app/learn/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AppLearnCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AppLearnCourseIdRoute
    }
  }
}

interface AppLearnCourseIdRouteChildren {
  AppLearnCourseIdLessonsLessonIdRoute: typeof AppLearnCourseIdLessonsLessonIdRoute
}

const AppLearnCourseIdRouteChildren: AppLearnCourseIdRouteChildren = {
  AppLearnCourseIdLessonsLessonIdRoute: AppLearnCourseIdLessonsLessonIdRoute,
}

const AppLearnCourseIdRouteWithChildren =
  AppLearnCourseIdRoute._addFileChildren(AppLearnCourseIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  AlumniRoute: AlumniRoute,
  CareersRoute: CareersRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EnginesRoute: EnginesRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  MarketplaceRoute: MarketplaceRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  ServicesRoute: ServicesRoute,
  StoriesRoute: StoriesRoute,
  VisitRoute: VisitRoute,
  WorkRoute: WorkRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppGradesRoute: AppGradesRoute,
  AppMessagesRoute: AppMessagesRoute,
  ApplyStatusRoute: ApplyStatusRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  CertificatesVerifyRoute: CertificatesVerifyRoute,
  PortalAcademicBoardRoute: PortalAcademicBoardRoute,
  PortalAccountantRoute: PortalAccountantRoute,
  PortalAdminRoute: PortalAdminRoute,
  PortalAdmissionsRoute: PortalAdmissionsRoute,
  PortalAlumniRoute: PortalAlumniRoute,
  PortalCareerServicesRoute: PortalCareerServicesRoute,
  PortalClientRoute: PortalClientRoute,
  PortalDataRoute: PortalDataRoute,
  PortalDeveloperRoute: PortalDeveloperRoute,
  PortalDevopsRoute: PortalDevopsRoute,
  PortalEmployerRoute: PortalEmployerRoute,
  PortalExecutiveRoute: PortalExecutiveRoute,
  PortalFinanceRoute: PortalFinanceRoute,
  PortalGovernmentRoute: PortalGovernmentRoute,
  PortalHrRoute: PortalHrRoute,
  PortalInstructorRoute: PortalInstructorRoute,
  PortalInternRoute: PortalInternRoute,
  PortalItSupportRoute: PortalItSupportRoute,
  PortalMarketingRoute: PortalMarketingRoute,
  PortalMentorRoute: PortalMentorRoute,
  PortalNgoRoute: PortalNgoRoute,
  PortalOperationsRoute: PortalOperationsRoute,
  PortalParentRoute: PortalParentRoute,
  PortalPartnerRoute: PortalPartnerRoute,
  PortalQualityRoute: PortalQualityRoute,
  PortalReceptionistRoute: PortalReceptionistRoute,
  PortalRegistrarRoute: PortalRegistrarRoute,
  PortalSecurityRoute: PortalSecurityRoute,
  PortalStudentRoute: PortalStudentRoute,
  PortalSupplierRoute: PortalSupplierRoute,
  PortalVolunteerRoute: PortalVolunteerRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsCompareRoute: ProgramsCompareRoute,
  AppIndexRoute: AppIndexRoute,
  ApplyIndexRoute: ApplyIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  AppAssignmentsAssignmentIdRoute: AppAssignmentsAssignmentIdRoute,
  AppInstructorAnalyticsRoute: AppInstructorAnalyticsRoute,
  AppInstructorAttendanceRoute: AppInstructorAttendanceRoute,
  AppInstructorGradebookRoute: AppInstructorGradebookRoute,
  AppLearnCourseIdRoute: AppLearnCourseIdRouteWithChildren,
  AppAssessmentsIndexRoute: AppAssessmentsIndexRoute,
  AppAssignmentsIndexRoute: AppAssignmentsIndexRoute,
  AppLearnIndexRoute: AppLearnIndexRoute,
  AppAssessmentsAssessmentIdTakeRoute: AppAssessmentsAssessmentIdTakeRoute,
  AppInstructorCoursesCourseIdRoute: AppInstructorCoursesCourseIdRoute,
  AppInstructorAssignmentsIndexRoute: AppInstructorAssignmentsIndexRoute,
  AppInstructorAssignmentsSubmissionIdGradeRoute:
    AppInstructorAssignmentsSubmissionIdGradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
